### ISSUE TITLE
Remove interactive menus?

### ISSUE THREAD

**Issue by mchelen** [jsonresume/resume-cli#100]
I'd like to suggest the removal of interactive menus. They are inconsistent with most command line utilities where all parameters are supplied through command line switches. Using interactive menus makes tasks slower, and harder to repeat or automate.
It might be ok to allow both switches and interacive menus, but this adds to the code complexity.
To promote standardization and simplicity, what does everyone think about completely removing the menus?

**Comment by erming** [comment]
I don't like them either.

Either options via `--to-html` or something like `Export format? [HTML/pdf]` with a default value.

_Or both!_

**Comment by mchelen** [comment]
Yup, for commands like `export` it already supports detecting file extensions, and allows `--format`.
Another important command is `resume init` which then prompts for name and email. Presumably those could be passed via `--name` and `--email` although I'm not totally clear on the point of prepopulating these fields when the initial `.json` has to be edited anyway.

**Comment by thomasdavis** [comment]
Let's go ahead with this =)

**Comment by erulabs** [comment]
I've been able to get around this with the following syntax: `resume export target.pdf`, which has no prompts.

**Comment by chrisdotcode** [comment]
Interactive menus will be removed in `v1.0.0`

**Comment by som3guy** [comment]
Will this be done for the publish option as well. 
I would like to be able to just run a command to publish rather than have to deal with an interactive menu.

**Comment by thomasdavis** [comment]
Interactive menus were removed.
