### ISSUE TITLE
Elegant theme includes education section, even if education isn't part of resume

### ISSUE THREAD

**Issue by traverseda** [jsonresume/resume-cli#105]
Also true of kwan. But elegant is the one I care about most.

**Comment by jaysonvirissimo** [comment]
The 'About' section is also displayed whether it is in the JSON or not.

**Comment by mchelen** [comment]
Please submit these issues to the theme's repo: https://github.com/mudassir0909/jsonresume-theme-elegant

**Comment by mudassir0909** [comment]
Created an issue about the same here https://github.com/mudassir0909/jsonresume-theme-elegant/issues/40

will fix it soon
