### ISSUE TITLE
Export to PDF seems to have stopped working?

### ISSUE THREAD

**Issue by ainsleychong** [jsonresume/resume-cli#107]
Hello, and thanks for the cool project =)

I noticed that the "resume export resume.pdf" functionality stopped working recently (exporting to html is fine).

In ./lib/exportResume.sendExportPDFRequest() it looks like you are sending the resume.json off to "http://registry.jsonresume.org" to create the PDF, so I can't debug much beyond that.

**Comment by ainsleychong** [comment]
Realized I'm missing some detail here.

I'm just trying to create a PDF from the default resume.json created when you run "resume init".

I believe it was working just yesterday, but doesn't seem to to be working today.

**Comment by ainsleychong** [comment]
Ok this is working again.

**Comment by OutThisLife** [comment]
Failing for me today.. is there a fix, or do you just wait?

**Comment by mchelen** [comment]
Please see https://github.com/jsonresume/resume-cli/issues/94
