### ISSUE TITLE
Heroku | No such app

### ISSUE THREAD

**Issue by Manju244** [jsonresume/resume-cli#109]
When i go to the link http://registry.jsonresume.org/thomasdavis in the morning giving error as,

Heroku | No such app

There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.

Can i know the reason!!!

**Comment by thomasdavis** [comment]
Bringing it back up now, Heroku issues, shouldn't be long.

**Comment by PeterDaveHello** [comment]
Looks fine now.

**Comment by Manju244** [comment]
Yes now it's fine. Thank you.
