### ISSUE TITLE
Pdf export shows website links twice

### ISSUE THREAD

**Issue by chrisgame** [jsonresume/resume-cli#111]
When exporting to pdf the urls under the website property a printed once and then again in brackets ().

**Comment by mistakenot** [comment]
+1 Would be nice to remove this

**Comment by emersion** [comment]
Bootstrap's `@media print` rules are printing links twice.

Templates can remove these rules with some JS code: https://github.com/emersion/jsonresume-theme-flat/blob/master/resume.template#L10
