### ISSUE TITLE
Need to reset theme after every publish 

### ISSUE THREAD

**Issue by antsankov** [jsonresume/resume-cli#115]
Everytime I want to make a change to a resume and publish it to my web profile, it seems to be published with the [flat theme](http://themes.jsonresume.org/theme/flat). To get to another theme to work, I need to run ```resume settings```, select the theme I want and then republish. I have to repeat this process for every republish. 

Possible Solutions: 
- Store information with account about last used theme. 
- Stored some data locally about last selected theme. 

I like what you all are working on, and if pointed in the right direction, I would be happy to make some of these changes.

**Comment by mchelen** [comment]
Can anyone confirm this? It used to have no problem saving the theme.

**Comment by chrisdotcode** [comment]
Will be fixed with #127.
