### ISSUE TITLE
"ERROR: No API conversion tokens available"

### ISSUE THREAD

**Issue by ogregoire** [jsonresume/resume-cli#116]
I created a new resume and I got the following error in the PDF file, as TXT file.

> ERROR: No API conversion tokens available

The list of commands I used, in order:

    $ resume --help
    [...]
    $ resume init
    [...]
    $ resume test
    [...]
    $ resume export cv.pdf --format pdf --theme modern
    
          running validation tests on resume.json ... 
    
      ✓ Passed all validation tests. 
    
    To publish your resume at http://jsonresume.org type the command resume publish
    -
    Done! Find your new .pdf resume at /home/olivier/Documents/CV/jsonresume/cv.pdf
    $ cat cv.pdf
    ERROR: No API conversion tokens available

**Comment by mchelen** [comment]
https://github.com/jsonresume/resume-cli/issues/94
