### ISSUE TITLE
Go through and push tags for each release

### ISSUE THREAD

**Issue by dbkaplun** [jsonresume/resume-cli#122]

**Comment by rolandnsharp** [comment]
Hi again @dbkaplun , can you please link me someplace that will walk me through this process. I've never used tags before and I'm about to release a new version.

**Comment by dbkaplun** [comment]
Sure, the difficult part is finding the commits that increased the version number. When you're on a version-changing commit, run `git tag <version>`, then when you're done, run `git push origin --tags` to push the tags. I also recommend running `npm publish` but beware that npm will use the *most recently published* version so start from the beginning when publishing.

(For those who don't know, a tag is simply a reference to a commit, much like a branch, but committing when checked out to a tag won't change the tag.)

**Comment by chrisdotcode** [comment]
This seems like a lot of work. Can we just do this, going forwarding instead?

**Comment by thomasdavis** [comment]
Fixed in recent work.
