### ISSUE TITLE
Error launching `resume serve`

### ISSUE THREAD

**Issue by Bit32** [jsonresume/resume-cli#125]
Trying to create an upstart job with which to start/stop `resume serve` 

Launching resume on the commandline from the theme directory works, however when launched via upstart i receive the following error message in the logs:

```
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'undefined/.jsonresume.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at writeToConfig (/usr/local/lib/node_modules/resume-cli/lib/version.js:9:8)
    at checkVersionAndSession (/usr/local/lib/node_modules/resume-cli/lib/version.js:35:9)
    at /usr/local/lib/node_modules/resume-cli/lib/waterfallArray.js:59:9
    at fn (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:638:34)
    at Object._onImmediate (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Contents of /etc/init/resume.conf:

``` 
start on runlevel [2345]
stop on runlevel [016]
respawn

chdir /path/to/my/resumethemedir

# Specify the process/command to start, e.g.
script
        cd /path/to/my/resumethemedir        
        exec resume serve
end script
```

Replacing 'exec resume serve' with another command appears to work fine, for example replacing it  with `exec ls -la` lists the contents of theme directory as would be expected.

**Comment by rolandnsharp** [comment]
Hi @Bit32 , this must be an issue with the resume-cli not being able to find your home directory with your config file (.jsonresume.json) in it.

This is the code we currently use to find the home directory.
`var homeDir = process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];`

So it may not be able to resolve process.env with upstart (i don't know what upstart is).

Any idea on what the fix may be?

**Comment by Bit32** [comment]
Hey Roland, 

Sorry about the late reply - it appears I wasn't notified of a follow up. Also many thanks for your response - it's much appreciated, as I had reached a dead end with this before. 

I'm happy to say though that today, after upgrading to the current version of resume-cli, this issue appears to be resolved :)

Ps. Upstart is the init daemon for Ubuntu. I am using it to configure 'resume serve' as a service that will run automatically at boot/reboot
