### ISSUE TITLE
Customising PDF generation

### ISSUE THREAD

**Issue by mistakenot** [jsonresume/resume-cli#126]
Is there any way to specify the options used for generating the PDF? Specifically things like page width, page size, zoom etc?

**Comment by enahs** [comment]
I used phantom.js to get around this. pretty janky but if you output to HTML then you can use phantom to render the page and take a nice PDF capture. wkhtmltopdf is trash; don't waste your time.

**Comment by thomasdavis** [comment]
If you print to pdf in chrome, you can control zoom, margins etc
