### ISSUE TITLE
Ability to change the default theme

### ISSUE THREAD

**Issue by entropitor** [jsonresume/resume-cli#127]
Currently, you can only set your default theme, to one of 3 default themes (flat, modern, elegant), while `--theme fizz` for example works fine from the command line. So it would be nice if we could select for example `fizz` as our default theme.

**Comment by mudassir0909** [comment]
```
resume publish --theme fizz 
```
would set your resume to default fizz theme, is it not doing that or you want something else ?

**Comment by caske33** [comment]
So this only works for publishing your resume? Because it would be useful if it was also respected with pdf export etc. 

And the main reason I would want this, is so I could change my resume, without having to lookup, whichever theme I liked most. Or is there some way of specifying this in the resume itself?

**Comment by mudassir0909** [comment]
```
resume export [filename] --theme fizz 
```
should export the pdf with fizz theme.

Oh I think I just got what you are trying to say, you want to set the theme to say "fizz" at the account level as your default theme so that every time you publish you wouldn't have to pass in `--theme` option, correct ?

**Comment by caske33** [comment]
Indeed. (and the same for the export command). If the theme flag is not passed, it should default to your account default.

And we would also need a way of selecting, for example fizz, as the default for an account. Which is currently nog possible either.

**Comment by rolandnsharp** [comment]
Nice suggestion @caske33 , I'll work on implementing this with the next version release.

**Comment by mudassir0909** [comment]
@caske33 :+1:

**Comment by rolandnsharp** [comment]
@caske33 , what commands would you like to use to set a default theme to the config file?

Or would this better suit the settings menu: `Set Default Theme` -> `Enter theme name:`

Something like that?

**Comment by caske33** [comment]
Just a suggestion, but this could work:

`resume settings`: open the menu
`resume settings <get|set> <option> <value (in case of set)>` for example `resume settings set theme fizz` to set the default theme to fizz.

although, the terminal menu should probably also mention the option to set other themes. I like the `add theme` option the most.

**Comment by rolandnsharp** [comment]
@caske33 nice suggestion, you can see what I have so far here: https://github.com/jsonresume/resume-cli/pull/131

It's a settings terminal menu CHANGE THEME -> ADD THEME - Enter theme name:

Approve? I'll think about adding a command  options.

**Comment by caske33** [comment]
Seems fine. 

ADD THEME is maybe not perfect, but I think it's quite clear. (Can't think of another option)

I wouldn't always prompt for email and password, as the "default" theme should probably also work on `resume export` for which you shouldn't need an account (in my opinion).

**Comment by rolandnsharp** [comment]
Yeah, I wouldn't prompt email and password when exporting. But that makes me think of something that I've overlooked. CHANGE THEME changes the theme on the registry server (and stores a default), what if the user didn't have an account and only wanted to change their local default theme...

This is getting complicated. Maybe CHANGE THEME only sets the theme in the config file, and afterward a prompt appears asking if you'd like to publish these changes to the server.

**Comment by caske33** [comment]
Oh, I wasn't aware that it changed something in the registry too.

Then I would change it like this:
- A user changes his theme
      - The user is logged in => saved to local file AND to the registry
      - The user is not logged in => the preference is saved locally only.
- A user logs in
       - If the user has a default theme set on his computer, the console ask him: "You've currently got 'fizz' selected as your default theme. Would you like to save this to the registry? [Yn]"
- When a user exports to a file, or pushes to the registry
       - If the --theme flag is used, follow this
       - Otherwise, if the default theme is set locally, use that
       - Otherwise, if the user is logged in, and a theme is set in the registry, use that.
       - Otherwise fall back to the overall default.

**Comment by rolandnsharp** [comment]
Thanks for your input, this is going to be a bigger change than I expected. I'll merge my work anyway so that we have something to work with while I think about the best way to implement this.
