### ISSUE TITLE
[SyntaxError: Unexpected token ?]

### ISSUE THREAD

**Issue by deepfelt** [jsonresume/resume-cli#132]
I get this error when I try to run any of the resume-cli commands.  I have used multiple JSON validators and there are no errors in the resume.json file.

**Comment by dbkaplun** [comment]
What theme are you using? It's probably a theme error.

**Comment by deepfelt** [comment]
hmm i didn't even specify a theme

**Comment by PeterDaveHello** [comment]
Can you provide more info in detail?

**Comment by deepfelt** [comment]
I figured it out. It was something in the JSON.  Thanks!
