### ISSUE TITLE
Profiles section generates wrong link when exporting HTML

### ISSUE THREAD

**Issue by luciano-fiandesio** [jsonresume/resume-cli#133]
The profile section generates the following link: **file:///john** when I export to HTML.
The profiles section has the following data:

```
"profiles": [
 {
     "network": "Twitter",
     "username": "john",
      "url": "http://twitter.com/john"
 }
```

The same problem appears with other profiles, like github, etc.

**Comment by shaun10** [comment]
Would help if you provide all of profiles list and system and build specs.

**Comment by luciano-fiandesio** [comment]
System: __OSX 10.10.4__
Resume - __0.3.13__
npm - __2.10.1__

"profiles": [
 {
     "network": "Twitter",
     "username": "john",
      "url": "http://twitter.com/john"
 },
{
 "network": "Github",
     "username": "john",
      "url": "http://github.com/john"
}

**Comment by shaun10** [comment]
Can you try upgrading to latest commit, and doing another export. You might need to reinitialize the json. FYI, all those links use https://

**Comment by olivif** [comment]
This seems to work for me now. Does it repro for anyone else?

**Comment by chrisdotcode** [comment]
Closing until able to reproduce. Thanks, @olivif.

**Comment by PeterDaveHello** [comment]
@olivif what's the environment you are using? All the same as @luciano-fiandesio said?

@luciano-fiandesio do you still have this problem?

**Comment by olivif** [comment]
@PeterDaveHello  I'm running Windows 10, resume - 0.4.8, npm - 2.14.7.

**Comment by PeterDaveHello** [comment]
Thanks @olivif
