### ISSUE TITLE
resume test not reliable

### ISSUE THREAD

**Issue by PeterDaveHello** [jsonresume/resume-cli#135]
I'm sure I have a json that passed the [JSONLInt Validator](http://jsonlint.com/) but failed in resume-cli, and resume-cli didn't say any useful info, just number of failed test.

**Comment by clarkguru** [comment]
Same here

**Comment by PeterDaveHello** [comment]
Should be fine now:
https://github.com/jsonresume/resume-cli/compare/bf51b3df854b914cb9de50fcbcd62cf63631c607...9ee609cf0728091e59b45f050e15f44fa187a193
