### ISSUE TITLE
After updating to latest commit ENOENT error when running export

### ISSUE THREAD

**Issue by shaun10** [jsonresume/resume-cli#136]
resume export resume.html
{ [Error: ENOENT, no such file or directory '.env'] errno: -2, code: 'ENOENT', path: '.env', syscall: 'open' }

  running validation tests on resume.json ... 

  ✓ Passed all validation tests. 

To publish your resume at http://jsonresume.org type the command resume publish
Unable to extablish connection to the theme server.
Check your network connection

Anyone else getting this?

**Comment by PeterDaveHello** [comment]
+1

**Comment by shaun10** [comment]
Running OSX 10.10.3 (14D136) related to registry updates in latest commit?

**Comment by karimhossenbux** [comment]
+1, same issue here

**Comment by alimehdi92** [comment]
+1, I tried it on both OSX and Linux,

**Comment by thomasdavis** [comment]
I've fixed that error and published 0.4.4

Think there are some other regressions that I'm investigating

**Comment by thomasdavis** [comment]
And some more fixes in 0.4.7

@rolandnsharp .dotenv isn't loading locally so the registry urls were a bit broke. I fixed them up  but they should also be moved to a central config file.

**Comment by shaun10** [comment]
Nice working well now. Thanks Thomas!

**Comment by PeterDaveHello** [comment]
So is it fixed?

**Comment by chrisdotcode** [comment]
@thomasdavis said above,
>  I fixed them up but they should also be moved to a central config file.

**Comment by PeterDaveHello** [comment]
> they should also be moved to a central config file.
So I think it's not done.

**Comment by chrisdotcode** [comment]
Well, I think the original issue is done, no? And the fact that they should be moved to a separate config file is another issue, you don't think?

**Comment by PeterDaveHello** [comment]
Okay, that's fair.
