### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by joryhatton** [jsonresume/resume-cli#140]
Is there a way to reset your password?  I forgot my old one, and I can't change it on my account. I would also like to change my resume to password protected and cannot figure out how.  Thanks.

**Comment by humansounds** [comment]
Any thoughts here?

**Comment by antsankov** [comment]
+1

This should be a feature.

**Comment by chrisdotcode** [comment]
This seems to belong [here](jsonresume/registry-server#77).
