### ISSUE TITLE
Need internationalization support for resume templates

### ISSUE THREAD

**Issue by Jaskey** [jsonresume/resume-cli#141]
Can I have internationalizatiion support on the templats? 

For example, the content of my working experience can be Chinese since I can provide the Chinese value for "work". But what about “Work” itself? I need to translate it into Chinese "工作经历" . 

 Is it possible now? How could I set up that?

**Comment by chrisdotcode** [comment]
I believe this is possible by just changing the value from whatever template you're using from "Work" to "工作经历" .

The current way to do this is to modify an already existing template, and push it up to npm.

More information [here](https://github.com/jsonresume/resume-cli/issues/161#issuecomment-156213731).

In so far as i18n for templates in general, I think that's a decision for the actual template author to support.

**Comment by Jaskey** [comment]
@chrisdotcode I tried at the json editor to replace the "key" from work to "工作经历", it doe not work. This is the json key, how can it replace into something else? In order to make it works ,there should be somewhere else to config its display.

**Comment by chrisdotcode** [comment]
No, not with the JSON editor, with the theme of your choice.

The "work" field in the actual resume.json should not be replaced - instead, when you render it with a theme, that theme can handle i18n for you.
