### ISSUE TITLE
Build(failed) on travis-ci

### ISSUE THREAD

**Issue by PeterDaveHello** [jsonresume/resume-cli#145]
Now all the builds failed ...

**Comment by chrisdotcode** [comment]
Since random isn't really reproducible, I'm going to close this for now.

@PeterDaveHello , if this happens again/if I'm wrong, can you re-open this with an error log, please?

**Comment by PeterDaveHello** [comment]
I think it's not only random now.

**Comment by PeterDaveHello** [comment]
https://github.com/jsonresume/resume-cli/commit/45a521a24a4805f6977600fabf98049aaf4e3b57 make it passwd lol

**Comment by PeterDaveHello** [comment]
Got it again: https://travis-ci.org/jsonresume/resume-cli/jobs/91519603
