### ISSUE TITLE
Cannot publish to my account

### ISSUE THREAD

**Issue by gabewonders** [jsonresume/resume-cli#149]
When I try to publish to my account it prompts me to enter my login details below. But when I enter in the first key it immediately kicks me out of the prompt. I have registered an account, done a `resume init` and have a `resume.json` file. Any ideas why this is happening?

Please note I am able to publish as guest without any issues.

**Comment by angelocordon** [comment]
Having the same issues, I'm getting this error message in my terminal: 

_stream_readable.js:730
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:730:11)
    at ReadStream.Readable.resume (_stream_readable.js:715:3)
    at new Interface (readline.js:142:9)
    at Object.exports.createInterface (readline.js:39:10)
    at read (/usr/local/lib/node_modules/resume-cli/node_modules/read/lib/read.js:45:23)
    at async.series.email (/usr/local/lib/node_modules/resume-cli/lib/publish/index.js:88:25)
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:689:13
    at iterate (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:265:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:284:9)
    at _parallel (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:688:9)
    at Object.async.series (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:710:9)
    at /usr/local/lib/node_modules/resume-cli/lib/publish/index.js:86:%

**Comment by gabewonders** [comment]
I was receiving the "Cannot switch to old mode now." error but I updated node on my mac and now I do not receive that message just the error I described in my comment.

**Comment by angelocordon** [comment]
Thanks @gabewonders that worked!

**Comment by ebenoist** [comment]
@gabewonders I'm seeing the exact same issue. When I run `resume register` and select to publish to my account. Any key click halts the program silently.

```
[~]❥ node -v
v0.12.7
```

```
[~]❥ resume publish

  running validation tests on resume.json ...

  ✓ Passed all validation tests.



             PUBLISH MENU
     ------------------------------
     Publish to your account.
     Publish as guest.
     Publish to your account (password access).
     Publish as guest (password access).
     ------------------------------
     EXIT

     To acquire account details, press ^C and type: `resume register`
     Or just publish as guest.

SELECTED: Publish to your account.

To acquire login details use the command: `resume register`
If you already have an account, enter your login details below:
email: (ebenoist@gmail.com) [~]❥
```

**Comment by thrash4life** [comment]
Word up. Same error here. I'm on c9.io and I've used both v4.1.0 and v0.12.7 NodeJS versions which result in the same behavior described above. Thankfully, first of all for a great service (even with its quirks) and second, I can at least publish as guest for the time being.

**Comment by SingleShot** [comment]
Any word on this?

**Comment by aliirz** [comment]
:+1: Can we please get this resolved. Facing the same issue as @ebenoist

**Comment by DetreRaison** [comment]
First time ever trying to upload to github, I've been having countless problems trying to commit and upload my source. It'd be nice since If the software provided for window users actually worked, and I'm 100% my login info is correct it's a problem with the client.

**Comment by chrisdotcode** [comment]
Yes, this happens to me, too with node v4.1.1

I'm *guessing* that this is because the current cli version is relying on deprecated stream functionality. I'll see what I can do. If anyone can provide some more information in the interim, that would be great.

**Comment by lisli** [comment]
I'm having this same issue. Should I update node? Just publish as guest for now?

**Comment by chrisdotcode** [comment]
The state of the server is not the best at the moment. We'll work on that - but in the interim, hang tight guys.

**Comment by aliirz** [comment]
How can I help?

**Comment by chrisdotcode** [comment]
@aliirz We might end up needing to re-write/refactor parts of the resume server - so if you'd like to take a look ahead of time, you can do so :)

**Comment by dawsonbotsford** [comment]
Having the same problem. With my techincal situation fitting @gabewonders very first message. Hoping for a fix. Following this closely in the meantime. Thanks for working on such a cool idea!

**Comment by xdev2381** [comment]
Facing same issue here..:(

**Comment by rohit-prajapati** [comment]
Facing the same issue

**Comment by aliirz** [comment]
lets get to work folks. @chrisdotcode lead us to glory!!! tell us where to start

**Comment by chrisdotcode** [comment]
Hey, everyone!

@aliirz, right now, we're first going to finish `v1.0.0` of the schema first entirely, and then work on the CLI. It's easier to have a frozen specification before trying to change a single line of the CLI. We'd love it if you could help us close issues/PR the changes happening over in [jsonresume/resume-schema](https://github.com/jsonresume/resume-schema).

**Comment by so0k** [comment]
same issue here, I'm running in a Docker container `node -v` 

```
v.0.12.4
```

I don't see terminal errors.

**Comment by john-hu** [comment]
I got the same issue with node `v0.12.9` and `v5.4.1`

**Comment by andisab** [comment]
I was able to get around the error by repeating "resume login", then "resume publish" with "Publish to your account."

**Comment by thrash4life** [comment]
I can validate @andisab workaround. Awesome!

**Comment by CPME** [comment]
I can also validate @andisab , though my published page is blank, and I'm not sure why.

**Comment by thomasdavis** [comment]
Merging this thead into the other publishing issue thread -> https://github.com/jsonresume/resume-cli/issues/189

For anyone looking, as @andisab said above.

The way to publish right now is to `resume login` and then `resume publish` using the first option.

I am working on fixing all the commands today.

**Comment by chrisdotcode** [comment]
(Closing auto-manually because after 4 years, this might no longer be relevant. If this still does concern anyone, give me a holler.)
