### ISSUE TITLE
Registry: Heroku | No Such App

### ISSUE THREAD

**Issue by Billiam** [jsonresume/resume-cli#151]
Visiting http://registry.jsonresume.org/ returns a no such app error, affecting resume exporting, etc.

**Comment by PeterDaveHello** [comment]
Still not working? I have no problem here.

![screenshot from 2015-08-28 13 54 43](https://cloud.githubusercontent.com/assets/3691490/9540033/61033fa0-4d8c-11e5-9546-0ce17ef4d5ea.png)

**Comment by Billiam** [comment]
Back up and responding, closing.
