### ISSUE TITLE
Host issues

### ISSUE THREAD

**Issue by wr0ngway** [jsonresume/resume-cli#159]
I haven't been able to generate a resume using resume-cli for the past couple of days - it just generates an nginx 500 error page using the command (with or without theme, using v0.4.8):

    resume export --theme Kwan resume.html

**Comment by wr0ngway** [comment]
Hmm, I guess its something wrong inside my json as the freshly generated json from "resume init" exports just fine - maybe preserve this as a issue against the error reporting?

**Comment by wr0ngway** [comment]
Ok, maybe not something wrong with my json - it fails as-is for this json: http://wr0ngway.github.io/resume.json

If I remove the TivoHMO section under publications, it succeeds

**Comment by thomasdavis** [comment]
Our dns host Cloudflare seemingly has had some issues, I'm looking into it.

On Thu, Oct 1, 2015 at 9:10 AM, Matt Conway <notifications@github.com>
wrote:

> Ok, maybe not something wrong with my json - it fails as-is for this json:
> http://wr0ngway.github.io/resume.json
>
> If I remove the TivoHMO section under publications, it succeeds
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsonresume/resume-cli/issues/159#issuecomment-144570837>
> .
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by mchelen** [comment]
For reference, the site that isn't working seems to be http://themes.jsonresume.org/
For example:
http://themes.jsonresume.org/theme/elegant
http://themes.jsonresume.org/theme/paper
http://themes.jsonresume.org/theme/kendall
etc.

**Comment by thomasdavis** [comment]
Damn host issues, had heaps lately, working on it.

On Fri, Oct 9, 2015 at 11:03 PM, Mike Chelen <notifications@github.com>
wrote:

> For reference, the site that isn't working seems to be
> http://themes.jsonresume.org/
> For example:
> http://themes.jsonresume.org/theme/elegant
> http://themes.jsonresume.org/theme/paper
> http://themes.jsonresume.org/theme/kendall
> etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsonresume/resume-cli/issues/159#issuecomment-146865333>
> .
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by thomasdavis** [comment]
So got it back up and working  seems like the latest version of elegant is down though.

**Comment by mudassir0909** [comment]
Elegant is up & running now.
