### ISSUE TITLE
Converted resume 

### ISSUE THREAD

**Issue by errakeshpd** [jsonresume/resume-cli#161]
```
resume export myresume.pdf --theme kendal-fix --force
```

converter resume contain  only this "Theme could not be found in the npm registry."

**Comment by chrisdotcode** [comment]
The current way the theme parser works is that it looks in the npm registry for your theme, and then uses that to render your resume.

At the moment, [jsonresume-theme-kendal-fix](https://www.npmjs.com/package/jsonresume-theme-kendal-fix) doesn't exist.

Also, check out #51 if you'd like to help.
