### ISSUE TITLE
duration calculation

### ISSUE THREAD

**Issue by oupala** [jsonresume/resume-cli#163]
How is calculated a duration between a startDate and an endDate?

When I use this json:

```json
"startDate": "1999-09-01",
"endDate": "2000-03-01",
```
I get the following result in my resume:

> Sep, 1999 - Mar, 20005 months

It should be 6 or 7 months, depending on how the duration is calculated, but not 5 months !

**Comment by dbkaplun** [comment]
@oupala what template are you using? JSONResume itself does no calculation, just validation.

**Comment by oupala** [comment]
I'm using the elegant theme.

If JSONResume does no calculation, the calculation should comes from the theme. I find it strange that a theme does calculation, but why not...

I will then open a similar issue on the elegant theme repo.

**Comment by mudassir0909** [comment]
I'm closing this one, since this issue belongs to the theme
