### ISSUE TITLE
Dates as undefined

### ISSUE THREAD

**Issue by vfulco** [jsonresume/resume-cli#165]
More of an observation vs. criticism.  In many professional resume writing circles, the current thinking is to shorten dates down to years only as for longer resumes, specific months and days often do not matter.  It also helps the candidate if there were gaps in employment.

Running a test resume through with years only raises the following errors:

    ✗ work[0].startDate is undefined expected undefined
    ✗ work[0].endDate is undefined expected undefined
    ✗ work[1].startDate is undefined expected undefined
    ✗ work[1].endDate is undefined expected undefined
    ✗ work[2].startDate is undefined expected undefined
    ✗ work[2].endDate is undefined expected undefined
    ✗ work[3].startDate is undefined expected undefined
    ✗ work[3].endDate is undefined expected undefined

**Comment by vfulco** [comment]
Adding on, for many in between undergrad and grad, they may want to reflect summer positions simply as "Summer" for start date and "Year" for end date.  Some of the errors surfaced because of this labeling.  TIA.

**Comment by chrisdotcode** [comment]
This fix is already in the works. Thanks!

cf. jsonresume/resume-schema#198
