### ISSUE TITLE
Question: How can employers view Resumes located at the Registry?

### ISSUE THREAD

**Issue by kbdavis07** [jsonresume/resume-cli#166]
Hi,

Just wondering how can employers view Resumes located at the Registry?

I know I might be missing where this is mention but on the http://jsonresume.org website do not see any where about how to access the registry for viewing.

Has information on how to publish but not how to "consume" or view the resumes.

I see there are Stats on Resume Views:

Resume views 650,999

How are these viewed?

A person just shares their URL to their Resume?

**Comment by thomasdavis** [comment]
Yes, people just personally share their url at the moment and if it is publicly shared then bots will also index them for search engines.

We haven't fleshed out any terms of service for our hosted database at the moment so I didn't think it ethical to open it up at this point. That being said, the registry server is an open source project so anyone is free to host their own registry of where resume.jsons can be sent.

**Comment by thomasdavis** [comment]
That alternative registry would have it's own ToS and could make publicly searchable anyone who decides to host their resume there.

**Comment by kbdavis07** [comment]
Thanks for your reply.

I figure for now just publicly share URL of resume and it make sense if sharing on twitter and others the search engines and crawlers will also pick it up :)


I am interested in creating a centralized hub to both post and view resumes in JSON format.

So far have domain

http://resumerepo.com

I think with a  JSON formatted Resume can solve the issue of having a true one click solution for job seekers.

Even thinking of having self-hosted resumes where a person have their resume in json format on their own personal website and have an API that connects to 

http://resumerepo.com

So when the Resume.json file changes pings and updates in the system.

This way job seekers only have one centralize location to edit and update their resume.

Then it is feed to who ever is using the API feed.

**Comment by thomasdavis** [comment]
That sounds very ideal! We have been meaning for a long time to build out a hub that really works for users but haven't had the time.

Have a look at the registry code base to see how we originally structured things but I'd probably suggest a rewrite if you are building your own service.

The registry server at the moment forwards resume.jsons to the theme server which converts it into HTML to be rendered, you could merge these into one server also.

**Comment by vfulco** [comment]
Looking forward to seeing this happen (an accessible resume repository).  Would help with an ML like project (as a force for good) I am attempting.

**Comment by kbdavis07** [comment]
Found out Google is doing a great job indexing the resumes :)

Try this search query:

"asp.net mvc site:http://registry.jsonresume.org"

It returns lots of resumes from the Registry.

"Your Search Term   site:http://registry.jsonresume.org"

For now searches the Registry.

**Comment by kbdavis07** [comment]
Hi All,

Started a Repo for the Job Title and Skills Dictionary.

https://github.com/kbdavis07/voc

Please check it out and give feed back by posting it here:

https://github.com/kbdavis07/voc/issues/new


Have a great day!

**Comment by chrisdotcode** [comment]
I believe @thomasdavis already answered this question fully:

> People just personally share their url at the moment and if it is publicly shared then bots will also index them for search engines.

> Anyone is free to host their own registry of where resume.jsons can be sent.

> That alternative registry would have it's own ToS and could make publicly searchable anyone who decides to host their resume there.

So I'm going to close this now.
