### ISSUE TITLE
Export resume using elegant theme throwing 502 (Cloudflare) error.

### ISSUE THREAD

**Issue by codeocelot** [jsonresume/resume-cli#167]
For both .pdf & .html outputs.  I suspect it's also related to the entire theme.jsonresume.org site being down.  Any status on what's going on? 
![jsonresume_cloudflare error](https://cloud.githubusercontent.com/assets/4086894/10922401/bcd8b80a-822f-11e5-8731-f8202c4e1ea6.png)

**Comment by mudassir0909** [comment]
@codeocelot I think this is not happening now, maybe we can close this now?

**Comment by codeocelot** [comment]
hi @mudassir0909 problem's fixed.  Thank's for your response.

**Comment by codeocelot** [comment]
sorry gentlemen, I think only .html output's working.  .pdf export produces a .pdf file with ERROR: No API conversion tokens available  as it's contents.  Is this related?

**Comment by chrisdotcode** [comment]
Closing as duplicate. cf. #168

**Comment by chrisdotcode** [comment]
Sorry that I closed this. I thought this and #168 were the same. In reality, pdf rendering seems to be broken in two places.
