### ISSUE TITLE
pdf rendering is broken

### ISSUE THREAD

**Issue by vfulco** [jsonresume/resume-cli#168]
resume.json passes all tests then I am given the choice of .html or .pdf.  Choosing the latter creates a broken file with the error message, 

```
Unable to open :/file/foo.pdf File type HTML document (text/html) is not supported
```

The .html version works however when I try to print it to convert to pdf and then doc one of the 'work' fields and 'awards' fields shifts to the left which is not seen on the rendered html version making it useless.

**Comment by morenoh149** [comment]
I can reproduce this.

**Comment by kneeki** [comment]
I too can reproduce this.

**Comment by StevenBlack** [comment]
:+1: it's broken on OS X, latest.

**Comment by kneeki** [comment]
For those looking for a work-around, this was successful using Ubuntu 15.10:
1. terminal: sudo apt-get install wkhtmltopdf
2. resume export resume-paper.html -t Paper
3. terminal: wkhtmltopdf resume-paper.html test.pdf

**Comment by alexklibisz** [comment]
:+1: and thank you @kneeki !

**Comment by chrisdotcode** [comment]
We'll have these sorts of fixes documented/fixed entirely shortly.

**Comment by asymmetric** [comment]
The workaround posted by @kneeki doesn't seem to produce the same output as the HTML unfortunately.

**Comment by b-pmcg** [comment]
Using @kneeki suggestion is helpful, but as @asymmetric pointed out many themes lose their formatting, thus making wkhtmltopdf not a perfect solution. Are there any other html to pdf converters that maintain source formatting? Are there any other workflows people would be willing to share to format a json resume as a sendable document?

**Comment by GenericUK** [comment]
Any news on this issue? 

Resume 0.4.13
Ubuntu 16.04
Node  v6.2.0
NPM 3.8.9

**Comment by basiclaser** [comment]
I would love to integrate this into another OSS project, any news?

**Comment by thomasdavis** [comment]
It is just not an easy problem to solve. I could turn on the paid PDF API again but the results were actually pretty bad.

Turning dynamic HTML into PDF is just not the feasible. The themes have to be pretty explicit about how they render to PDF and only 1 or 2 of the themes in our ecosystem actually look half decent.

Or try @kneeki answer up above

**Comment by dbkaplun** [comment]
I've used  [`html-pdf`](https://github.com/marcbachmann/node-html-pdf) in the past with great success.

Pros:

* Does not require external API server
* Renders HTML as PDF using PhantomJS
* Easy to use

Cons:

* Not everything is configurable (specifically printing only certain pages is difficult/impossible without another library)
* Existing logic is based around API

Just throwing the idea out there as I'm very busy or I'd have a go at it myself. Maybe I will implement this as part of a bigger (needed) refactor down the line.

See also #72

**Comment by binarymist** [comment]
There seems to be a lot of echo system built around jsonresume, which made me think this looked like a successful project, so dived in and spent a few hours on it. Then finally attempted to export pdf via the CLI and it just doesn't work. It's probably a good idea to put on the readme that this core functionality is broken, before more new unsuspecting people do the same.

**Comment by thomasdavis** [comment]
Apologies for the inconvenience Kim, I've updated the homepage documentation to highlight that PDF export is currently broken. 

On a second thought, I'm only just coming to the conclusion that I don't know if we will ever have "PDF export". Themes are built by individual maintainers, and they each have to be specifically tailored to be able to render to PDF correctly. So we might have to update the homepage to reflect that only some particular themes support PDF export.

And on your second point, not only are most people too busy but those who do contribute also disappear after landing jobs. Though that is fine too, I personally believe JSON Resume will stand to gain from a slow project evolution. I've personally been quite content with my usage of the system. Thanks for the feedback!

**Comment by binarymist** [comment]
Yeah, I'm a contractor, so I'm constantly updating the CV, that's why a tool like this is good. Spent a day on the CV so far with this tool and getting some reasonable results.

**Comment by sr-ix** [comment]
I'm in a similar boat as @binarymist. Luckily only a few of the places I apply to allow only text documents (.doc, .pdf) in their online application portals. If they would all allow links to the resume I've made using this (otherwise wonderful) tool hosted online, maybe it'd be different.

A work-around I'm going with is honing one specific theme that is consistent when exported from html to pdf using @kneeki 's answer.

Still, a solution baked into the tool would be ideal.

**Comment by thezoid** [comment]
I noticed on the jsonresume website that this is 'currently broken, need help'. Have you tried using pandoc? It's GPL

**Comment by PeterDaveHello** [comment]
Let's move to #94
