### ISSUE TITLE
Ability to export locally

### ISSUE THREAD

**Issue by chrisdotcode** [jsonresume/resume-cli#169]
cf. #51 

Off the top of my head, I'm thinking of three possible ways to implement this:
1. Use a switch, `--local` or something, to specify that a local theme should be used instead.
2. Parse the variable given for `--theme`, and if it's an absolute path, use that theme, instead of hitting the server (remember, bash expands your `~`s and `./`s to absolute paths).
3. If the server doesn't have the theme, search locally for that theme instead.

Actually, maybe all of these can be used at once: you can either give an explicit `--local` flag, an absolute path, and if you don't, if the server fails to find your theme, it searches for a local one with the same name in some `$location`.

What does everybody else think?

**Comment by chrisdotcode** [comment]
I honestly think that the default resume-cli installation should come with a couple more themes, and search and render with those local themes *before* hitting either the json registry or npm registry.

I think being able to generate resumes offline is a sane default.

**Comment by chrisdotcode** [comment]
Any local theme needs to also make sure it's assets are in-file/localized, cf. #69.

**Comment by chrisdotcode** [comment]
@PeterDaveHello, can you share your thoughts on the matter, too?

**Comment by PeterDaveHello** [comment]
Sure I'll, please give me more time.

**Comment by chrisdotcode** [comment]
:+1:

@PeterDaveHello, are you available on IRC to chat?

**Comment by PeterDaveHello** [comment]
I think we have a gitter chat room
https://gitter.im/jsonresume/public

**Comment by olivif** [comment]
I definitely think it would be valuable to have the ability to export locally (and I like idea # 1 with the --local switch). Not sure I agree with this being the default though, if we want people to use the registry and the ecosystem (themes, etc.).

**Comment by kehugter** [comment]
# 1 sounds like the best approach to me.

> Actually, maybe all of these can be used at once: you can either give an explicit --local flag, an absolute path, and if you don't, if the server fails to find your theme, it searches for a local one with the same name in some $location.

Asking the server is too much IMO. Searching the provided path and $location sounds more reasonable for a `--local` flag.

**Comment by davidjb** [comment]
+1 for being able to use local themes and generate offline; would be extremely helpful for using a custom theme.

**Comment by thomasdavis** [comment]
You can already export locally if you have the theme downloaded.

Though if you are exported from a non theme dir, I simply made a request to the themes server. If the user doesn't want to hit our themes server, they will have to download the theme manually or the cli tool will have to do it.

Not really any difference except whether the user wants to make a http request to our themes server or to npm instead.

Personally I would rather just hit the themes server so that I didn't pollute my npm folder with themes all the time.

**Comment by kehugter** [comment]
> export locally [...] download the theme manually

Can you please explain how this is done? I can't figure out how to pass the cloned theme repo as an argument to resume-cli.

**Comment by JasonSwindle** [comment]
I agree. Can you give examples of making export work locally? Trying to export in the same directly as where my index.js (onepage git cloned) is, I still using the default theme.

**Comment by astephen2** [comment]
I actually just submitted a PR that does local export for both HTML + PDF with no ability to do server-side export at all. What's everyone's thoughts on that?

**Comment by JasonSwindle** [comment]
I love it.   It would make my CI/CD option for resume complete.  Currently I'm a bit stuck...

**Comment by arjanfrans** [comment]
I would like to see this option. Next to my resume.json, I want to have a directory containing a custom theme. I just want to load that and not having to publish it first.

**Comment by divyenduz** [comment]
Has anyone taken this up? I can take it up and add support for `--local=<path>` if no one is already working on it.
