### ISSUE TITLE
Add missing tags for each version

### ISSUE THREAD

**Issue by PeterDaveHello** [jsonresume/resume-cli#175]
This makes no sense:
![default](https://cloud.githubusercontent.com/assets/3691490/11201732/c55ad14c-8d1b-11e5-8ad5-7d0b628d152b.png)

**Comment by chrisdotcode** [comment]
I think we discussed this in one of the other repos. Unless someone wants to volunteer to do so, it seems like a lot of work. I suggest we just add tags for each version going forward.

**Comment by PeterDaveHello** [comment]
No problem and that's not in emergency, I'll take care of it.

**Comment by chrisdotcode** [comment]
:+1:
