### ISSUE TITLE
Provide JSON-LD and Schema.org implementations

### ISSUE THREAD

**Issue by BigBlueHat** [jsonresume/resume-cli#18]
You might want to give http://json-ld.org/ a look. It would let you map various defined vocabularies (Schema.org, Friend-of-a-Friend, etc) to elements in the resume JSON.

The advantage being that `bio.firstName` in resume JSON could more easily be mapped to `persone.first_name` in someone else's system.

Great start in any case! :smile:

**Comment by thomasdavis** [comment]
Discussion -> https://github.com/jsonresume/resume-schema/issues/42
