### ISSUE TITLE
Deleting resume published as guest

### ISSUE THREAD

**Issue by mtendotnet** [jsonresume/resume-cli#181]
Is it possible to delete a resume published as a guest?

**Comment by chrisdotcode** [comment]
I'm not entirely sure - currently the state of the server is... not where we want it to be. I would file an issue in the server's repo - but if not, hang tight for now, until we get stuff fixed.

**Comment by binarymist** [comment]
Was this done? I also have a guest resume published that I don't want.

**Comment by thomasdavis** [comment]
@binarymist I will track it down for you now Kim, sorry for the inconvenience.

**Comment by binarymist** [comment]
http://registry.jsonresume.org/ac5421d7
Thanks!

**Comment by thomasdavis** [comment]
Done and done!

**Comment by nguyendang1989** [comment]
https://registry.jsonresume.org/b4dba139
Please delete it.
Thanks!
