### ISSUE TITLE
Support HTML tags or Markdown format in json

### ISSUE THREAD

**Issue by hectorguo** [jsonresume/resume-cli#183]
When I tried to add some links in `summary`, I found that the html tag was escaped, may I have the chance to add html or markdown in the json file? 
Such as:
``` json
"work": [{
    "summary": "[My Website](http://website.com) or <a href=\"http://website.com\">My Website<\/a>"
  }
```

**Comment by hacksalot** [comment]
Not sure to [what degree this is supported in resume-cli](https://github.com/jsonresume/resume-cli/issues/40) yet, but in the meantime you could use [HackMyResume](https://github.com/hacksalot/HackMyResume) (which is JSON Resume compatible). It will do full Markdown conversion for HTML formats and basic inline conversion (bold, italics, hyperlinks) to WPML for MS Word (MD-to-LaTeX forthcoming). Downside is you're limited in terms of theme choice.

**Comment by chrisdotcode** [comment]
HTML/Markdown support is a job a theme - while I agree it's totally sane, the command-line tool itself isn't responsible for that conversion.

**Comment by chrisdotcode** [comment]
There was another comment here initially, but I'll have to look into what I said earlier. Hang tight for now.

**Comment by hectorguo** [comment]
I saw that the templates are based on handlebars, which can support for initial html tag. So I create a custom theme, just use `{{{summary}}}` or `{{&summary}}` instead of `{{summary}}`, and the html tag will not be escaped.

**Comment by mudassir0909** [comment]
@hectorguo What theme you are using?

**Comment by hectorguo** [comment]
@mudassir0909 I custom a [new one](https://github.com/hectorguo/jsonresume-theme-material) by myself.

**Comment by mudassir0909** [comment]
great :+1: 

I was about to say that if you create that issue on the respective theme repository to support markdown it'd be more helpful :)

**Comment by chrisdotcode** [comment]
So I think I was correct in what I was getting at before: themes are responsible for the content in the values of JSON Resume fields, and therefore, if a theme doesn't render markdown, it's because the theme doesn't support markdown.

Tangentially, all default themes that come with the cli (might/should)? render markdown and/or html. We'll have to reach a consensus on that one.

**Comment by mudassir0909** [comment]
Agreed, but it only makes sense to have all themes support the markdown else the output will vary as you change the theme. But we can't enforce all theme developers to support markdown

Maybe we can include a method inside https://github.com/jsonresume/theme-utils, something as follows

```js
resume = theme_utils.parse(resume, options)
```

This method can internally do markdown --> html conversion in addition to other things(date formatting etc) if required, this way it'll become easier for theme developers as well & all theme developers would be working on a consistent format of resume, what do you think?

If you are okay with this then, I'll push the changes today & maybe we can add this inside official theme development documentation

**Comment by chrisdotcode** [comment]
I agree with this. If there is to be a standard, we (the organization) should be responsible for choosing it.

And you can't really go wrong with markdown.

**Comment by mudassir0909** [comment]
True, do you have any comments/suggestions on [this issue](https://github.com/jsonresume/theme-utils/issues/5) ? All I need is one :+1: to start making the required changes as mentioned in the issue

**Comment by chrisdotcode** [comment]
IMO, I think that maybe we should leave theme discussions/decisions until after we release `v1.0.0`. Otherwise, it would just be another thing to keep track of while iterating.

**Comment by mudassir0909** [comment]
Agreed
