### ISSUE TITLE
Improve validation error messages

### ISSUE THREAD

**Issue by olivif** [jsonresume/resume-cli#184]
As stated in jsonresume/resume-schema#182 we need better error messages when validation fails. 

We need them for two main reasons: usability (users need to understand what is wrong and how they can fix it) and debuggability (we need to understand if we have any bugs in these cases or if these messages are indeed expected). 

This is probably an effort across both schema and cli, but I'm filing here as I hope we will get to this after schema v1 is finalized.

**Comment by chrisdotcode** [comment]
Hi everyone! Just got back from my holiday vacation. Expect roughly 40 github notifications. You're welcome.

- - -
Honestly, I'm feeling like the cli might need a gutting and a re-write. There are race conditions in odd places, the ncurses UI is deprecated, and we're going to be adding a lot of new features for `v1.0.0`.
