### ISSUE TITLE
Looking for tips on polishing up output

### ISSUE THREAD

**Issue by vfulco** [jsonresume/resume-cli#185]
Have tried a couple of different themes rendering .html and output comes out mangled.   The specific json file has been verified against schema and resume.schema.  Would appreciate any illumination on whether others are producing perfect, ready to ship output or if needed, what final tweaks and cleanup is done (which would seem to break the attempt at a fully automated process). Still very new to node.js world hence the questions.  TIA.

**Comment by chrisdotcode** [comment]
Hi there! This may not be your fault, as the internals of the CLI need a bit of work. We're working on fixing this :)
