### ISSUE TITLE
Only generating Richard Hendricks resume

### ISSUE THREAD

**Issue by chatels** [jsonresume/resume-cli#187]
It was recently working, but now only returns the demo resume when run with "resume export filename.pdf --theme short". There is a valid resume.json file in the current directory.

**Comment by thomasdavis** [comment]
What happens when you try just `resume export`

**Comment by chatels** [comment]
It asks for a filename, and then generates the Richard Hendricks resume again.

**Comment by chatels** [comment]
I found a missing comma in the Skills.Keywords array in my resume.json. Fixed the file and now it works. But weird that it compiles the demo resume on a formatting error.
