### ISSUE TITLE
Update to json file not getting reflected in http://registry.jsonresume.org/ URL

### ISSUE THREAD

**Issue by ksambhav** [jsonresume/resume-cli#188]
Updated my .json resume and publish using "resume publish resume.json". The steps completed successfully but the changes made do not get reflected in the web page.

Any clue how to get this fixed?

OS - Ubuntu 15.10
Node - 5.4
NPM - 3.3
resume - 0.4.8

**Comment by chrisdotcode** [comment]
As of now, the registry server isn't quite working, I think. This will be fixed.
