### ISSUE TITLE
Unable to publish resume

### ISSUE THREAD

**Issue by lobo-tuerto** [jsonresume/resume-cli#189]
Hello guys,

I'm on Ubuntu 15.10, and whenever I try to do a `resume publish` I get the menu, but if I select the `Publish to your account.` then I get the prompt asking for the email but whichever key I press it just drops to the bash CLI. So I'm not able to enter the email or other details.

It works for registering though.

Maybe it is related to https://github.com/jsonresume/resume-cli/issues/178

```
npm -v #3.3.12
node -v #v5.3.0
```

**Comment by hilalh** [comment]
It seems like the registry is down. Is this project still maintained?

**Comment by adrianblynch** [comment]
I had the same issue. Running `resume login` then trying to publish solved it.

@hilalh is right though, the registry is down at the moment.

**Comment by HeyCampbell** [comment]
Tagging @PeterDaveHello @rolandnsharp @erming 

Hoping that this is still maintained, if not maybe someone else can setup a public server. Just found this and think it's great

**Comment by thomasdavis** [comment]
Working on the server down problem, Heroku has kidnapped the domain name so
I can't reconfigure a new app at the moment, waiting for support.

On Fri, Jan 29, 2016 at 4:10 PM, Jon Campbell <notifications@github.com>
wrote:

> Tagging @PeterDaveHello <https://github.com/PeterDaveHello> @rolandnsharp
> <https://github.com/rolandnsharp> @erming <https://github.com/erming>
>
> Hoping that this is still maintained, if not maybe someone else can setup
> a public server. Just found this and think it's great
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsonresume/resume-cli/issues/189#issuecomment-176579013>
> .
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by PeterDaveHello** [comment]
We are waiting for the response from heroku, please wait and sorry for the inconvenience.

**Comment by HeyCampbell** [comment]
Thanks, for the response, guys, you've built something awesome here and I didn't want to see it go away!

**Comment by alnewkirk** [comment]
I'm experiencing this problem also. Thanks for being on top of this issue.

**Comment by lobo-tuerto** [comment]
Thanks @adrianblynch I needed to do `resume login`.

Now I have another problem, since it wasn't working before I registered another account using the same email. Now I have both URLs active (old and new `account name`) but can't switch `account name`. :(

**Comment by thomasdavis** [comment]
Victor can you send me the account names you want changed,
thomasalwyndavis@gmail.com

On Tue, Feb 2, 2016 at 12:38 PM, Víctor Adrián de la Cruz Serrano <
notifications@github.com> wrote:

> Thanks @adrianblynch <https://github.com/adrianblynch> I needed to do resume
> login.
>
> Now I have another problem, since it wasn't working before I registered
> another account using the same email. Now I have both URLs active (old and
> new account name) but can't switch account name. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsonresume/resume-cli/issues/189#issuecomment-178299430>
> .
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by ptsavdar** [comment]
Hello,
I'm having the same issue too. I cannot publish my resume via console. After choosing "Publish to your account" option it drops to the bash cli after pressing any key. Thank your for already trying to resolve the issue.

**Comment by lobo-tuerto** [comment]
@ptsavdar Did you try doing a `resume login` first? That solved my problem.

**Comment by alnewkirk** [comment]
I'm having the same problem as being reported here, and it also occurs when I try to reset my password. So I can't login, publish, or change my password.

**Comment by ptsavdar** [comment]
@lobo-tuerto Yes I tried, I logged in and only then I was able to publish my resume using the option `Publish to your account` without the `(password access)`.

**Comment by thomasdavis** [comment]
https://github.com/jsonresume/resume-cli/issues/195

**Comment by thomasdavis** [comment]
Copied from another thread


    The way to publish right now is to `resume login` and then `resume publish` using the first option.

I am working on fixing all the commands today.

**Comment by thomasdavis** [comment]
Anonymously publishing also works for me at the moment.

**Comment by thomasdavis** [comment]
Would anyone believe if I said I fixed this bug and published a new version to NPM?

Offending commit here -> https://github.com/jsonresume/resume-cli/commit/b87561ab32e96e7eed9f59e6a22988bacb841a89

New version 0.4.10

Would love some verification, make sure you on right version `resume --version`

**Comment by mikaelkaron** [comment]
Not working for me, on version 0.4.11 as `resume login` won't let me enter the password

**Comment by mikaelkaron** [comment]
Reinstall fixed my problem

**Comment by kushalj** [comment]
My jsonresume install recently shat itself and refused to publish, bombing out of the cmd line at the next keystroke after asking for my email. I installed older ones, new ones, 0.4.10 specifically and nothing helped. This was after a recent npm i -g resume-cli (which I did incase there was an update for PDFs). Uninstalling and reinstalling didn't work. Then suddenly it worked. I went through my bash history and (on OSX/iterm) this is what I had:

`resume export --theme kendall` This didn't work

`resume export --theme=kendall` This worked

this is different to the published docs:
![image](https://cloud.githubusercontent.com/assets/1095852/18232736/64b7a3a8-72ce-11e6-81c3-d20aca7fb564.png)

**Comment by jjatria** [comment]
Just to report that I still had the same problem with version 0.4.14. Using `resume login` first fixed it.

**Comment by ttelang** [comment]
Thanks .. I was also facing the same problem with my Windows 7 PC. 
Running resume login then trying to publish as advised above resolved it.

**Comment by joeytall** [comment]
resume login didn't work for me, 0.4.13 version works.

**Comment by mattolenik** [comment]
This is still a problem in 0.4.18. Doing "resume publish" as instructed by the documentation, and using the menu, does not work. It immediately drops to CLI. It works if resume login is done first, but then the published resume is blank. It worked fine locally.

**Comment by scirelli** [comment]
I'm not able to publish. On Mac OS X El Capitan. I registered, then 
`resume publish` 
select any option that requires email entry
Asks to enter email
Crashes as soon as I type one letter. Kicks me back to cmd prompt. No error messages.

**Comment by kushalj** [comment]
Also getting this. Try downgrading using nvm to 6, 5, 4.4.3, 0.12 (breaks), back to 7.2.1, everything works except 'Publish to your account (password access)' - regular publish works fine.

using:
`resume login`
`resume publish --theme=class`

no error message, as above.

**Comment by levitomer** [comment]
Hi Guys,

I'm having a similar issue with the resume publish command. After I'm publishing I am asking for typing my account details. But when I typing enter to continue in order to type my password, the console quits the authentication process when I press any key.

<img width="505" alt="screen shot 2017-05-02 at 3 50 27 pm" src="https://cloud.githubusercontent.com/assets/18260079/25618388/810f4392-2f4f-11e7-9ec9-6a28a8b5512b.png">

Is it some kind of a bug?

npm version: 4.2.0
Node version: 7.9.0

Attached a screenshot describing the last result of the authentication process.

Awesome feature btw!

**Comment by utkarsh-shekhar** [comment]
Hi all,

I believe I have found the cause of this issue. It is happening because it is trying to do an async request by calling the method "publishResume" in the case "customPublish". I have tried by wrapping it all inside async.series in my local copy and it works perfectly.
![screenshot from 2017-07-05 03-36-06](https://user-images.githubusercontent.com/5684840/27843616-3db50f1c-6133-11e7-84ad-95346951b42e.png)

**Comment by PeterDaveHello** [comment]
@utkarsh-shekhar cool! Wanna send a pull request?

**Comment by adamkarb** [comment]
If no one has submitted a PR for this yet I will

**Comment by compwron** [comment]
I am still having this issue. I tried using the code from @utkarsh-shekhar locally but I am still seeing the failure behaviour. :/  
nvm --version # 0.33.2
npm --version # 5.3.0
resume --version # 0.4.19

**Comment by JasonMFry** [comment]
Still having this issue. The workaround mentioned near the very top works (ie do `resume login` first, then `resume publish`, then choose `Publish to your account.`

**Comment by thomasdavis** [comment]
publishing was dropped in favorite of gist hosting -> https://jsonresume.org/getting-started/
