### ISSUE TITLE
claim an existing account and download the json

### ISSUE THREAD

**Issue by oren** [jsonresume/resume-cli#19]
after I created an account I want to continue updating the resume from a different machine, is it currently possible?

**Comment by sebDK** [comment]
Hi @rolandnsharp,

I m trying to update my json file from a different computer. I have to say that my resume was password protected. But when I am trying registry.jsonresume.org/yourusername.json, I have to write my password and after I get the following message:
```
You've made it this far, great!
But you still need to publish your resume

Create a new resume.json by typing `resume init`

Fill out a few of the fields until you are happy, then simply type `resume publish`
```

Any chance for me to get back my json file?

Thanks.

S.
