### ISSUE TITLE
Local Export maps to default Hendriks json

### ISSUE THREAD

**Issue by jducey** [jsonresume/resume-cli#190]
I was exporting my local JSON file without issue mid-week then the software updated at the end of the week and every time I perform an export Richard Hendriks data is exported not mine. I have validated that I do not have that JSON data on my local. I only have my data.

**Comment by CPME** [comment]
I've been having the same issue. I'm not even sure where it's pulling the Richard Hendriks data from because I don't have another "resume.json" file anywhere on my computer.

**Comment by aguang** [comment]
I also have this issue.

**Comment by thomasdavis** [comment]
In the same directory, when you type `cat resume.json` are you sure that is your resume?

**Comment by aguang** [comment]
yes

**Comment by brandevnull** [comment]
I was having this issue and I found that I just had a JSON validation issue. Seem like resume-cli should spit out an error in this case.

**Comment by AleksanderGrzybowski** [comment]
Same here, strange, cause first time I tried to render resume with json errors, it was spitting out default Hendriks resume, but later after removing whole folder with node_modules and reinstalling resume-cli locally it properly reported validation errors.
