### ISSUE TITLE
`resume export` error when IP is blacklisted by CloudFlare

### ISSUE THREAD

**Issue by ghost** [jsonresume/resume-cli#193]
I only tested this with `resume export example.html -t modern`. The generated HTML is CloudFlare's error message. I guess that the export should succeed only with a 200 response. In this particular case, CloudFlare sends a 403.

**Comment by thomasdavis** [comment]
Agreed, server errors should fail the command.

**Comment by hc-12** [comment]
Why is it contacting the server(s) when you're exporting *locally*??

There should be a disclaimer stating that resume-cli is contacting unknown sources on local export. It's highly unethical otherwise.

**Comment by TheLastProject** [comment]
I'm with @hc-12 on this one. It is rather nasty to send user data to a remote server without any kind of consent or notification. Despite that it makes the application extremely unreliable, it is just not cool to deal with user data so carelessly.

**Comment by kehugter** [comment]
Related: #169

Even though they're processing a lot of personal data, I don't see much interest in privacy from the devs. There's not even a privacy notice in the official site or the repos. I chose to stay away from this project for good.

**Comment by thomasdavis** [comment]
Will take these notes into consideration for the next iteration of theme exporting.
