### ISSUE TITLE
CLI tool rewrite

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-cli#194]
For anyone following along, @rolandnsharp and I have fell off the bandwagon over the last year and development has slowed to a halt.

At this point, it might be worth starting a new CLI project with someone else as the lead developer and writing it in es6 and other more modern conventions with a focus on minimalism and modularity.

If anyone is excited with the idea of writing a new clean CLI tool that works, chime in now!

**Comment by willpracht** [comment]
This would be great.

**Comment by thomasdavis** [comment]
Actually, just going to patch things for now, but will keep this open in case there are ideas floating about...
