### ISSUE TITLE
Resume publish fails to publish to jsonresume.org

### ISSUE THREAD

**Issue by ambitious-candidate** [jsonresume/resume-cli#195]
The tool presents 4 choices, and silently returns to shell once the choice is made. Tested on ``Ubuntu 32, 64`` and ``Windows 10`` using long and short user names.

**Comment by Topplestack** [comment]
This has been happening to me on almost every cli command. Resume settings kicks me out after making a selection as well. I'm running OSX - El Capitan. I'll spin up a linux VM and check check it out there.

**Comment by thomasdavis** [comment]
Merging this thread with the other main one.
