### ISSUE TITLE
themes.jsonresume.org is down

### ISSUE THREAD

**Issue by ArnaudRinquin** [jsonresume/resume-cli#196]
The service can't be reached, CloudFlare errors are displayed instead and themes can't be downloaded

**Comment by thomasdavis** [comment]
Oh boy this server has broken. Apparently the ec2 storage is non functional. (never seen that error before). Provisioning a new box.

**Comment by thomasdavis** [comment]
A new box is running -> http://themes.jsonresume.org/theme/flat should be back up.

**Comment by ArnaudRinquin** [comment]
Great! Thanks!
