### ISSUE TITLE
ERROR: No API conversion tokens available

### ISSUE THREAD

**Issue by bhanurao** [jsonresume/resume-cli#197]
Hi 
I'm trying to export to PDF using the command 
**$ resume export cv.pdf -t "Shorter"**
However when file is generated all it has is - **ERROR: No API conversion tokens available**
Regards
Bhanu

**Comment by bhanurao** [comment]
Duplicate issue

**Comment by GabLeRoux** [comment]
Duplicates #201

**Comment by PeterDaveHello** [comment]
Let's move to #201
