### ISSUE TITLE
Support YAML easily

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-cli#20]
The CLI shouldn't really care if it's YAML/JSON too much, just convert YAML to JSON and then continue as such with commands

**Comment by adius** [comment]
I'd love to see this implemented!
Just like @davidjb says:
> YAML is great and so much more readable/hand craftable than JSON.

**Comment by jjshoe** [comment]
@erming can't see using this without yaml support, writing JSON is more painful than just typing it up in word and converting to PDF.

**Comment by ad-si** [comment]
It has been 4 years since my last comment, and I'm still interested in this 😂

**Comment by TechQuery** [comment]
If JSONResume CLI supports **reading from `stdin`**, it'll be easier for us to use with an **YAML CLI parser** (such as https://www.npmjs.com/package/yamljs).

**Comment by pinage404** [comment]
i did a package to transform a folder of YAML's files to one `resume.json`

this allow to have 1 file per item (such as: experience or education)

after the end date of an item, there is few reason to update it

separating in files, seems simpler to manage them

https://www.npmjs.com/package/yaml-folder-2-jsonresume
