### ISSUE TITLE
http://registry.jsonresume.org/ not working | 503 Service Unavailable

### ISSUE THREAD

**Issue by ksambhav** [jsonresume/resume-cli#200]
http://registry.jsonresume.org/ is not showing the resume.

Request URL:http://registry.jsonresume.org/kumarsambhavjain
Request Method:GET
Status Code:503 Service Unavailable
Remote Address:104.28.17.105:80

Cache-Control:no-cache, no-store
CF-RAY:28cbcc1c78642df1-BOM
Connection:keep-alive
Content-Type:text/html; charset=utf-8
Date:Fri, 01 Apr 2016 11:46:22 GMT
Server:cloudflare-nginx
Transfer-Encoding:chunked

**Comment by thomasdavis** [comment]
Working on it
