### ISSUE TITLE
ERROR: No API conversion tokens available

### ISSUE THREAD

**Issue by ksambhav** [jsonresume/resume-cli#201]
Trying the .pdf url - [http://registry.jsonresume.org/kumarsambhavjain.pdf] is giving an error - "ERROR: No API conversion tokens available".

The command line `resume export abcd.pdf` does says :-

> Done! Find your new .pdf resume at:

but the generated .pdf doesn't open up and seems to have size of just 1 kb.

**Comment by lindell** [comment]
This problem do exist even for the example provided on the homepage.

https://jsonresume.org/getting-started/
http://registry.jsonresume.org/thomasdavis.pdf

Using the print to PDF version in chrome or another browser works just fine but it's harder to automate this process.

**Comment by rkazakov** [comment]
Still not solved?

**Comment by lindell** [comment]
@rkazakov Does not seem like it :/

**Comment by grug** [comment]
+1 I'm still getting this error.

**Comment by jsilter** [comment]
I just installed and I'm getting this error with command line export

**Comment by grug** [comment]
Are there any ideas on how to resolve this? I'm happy with submitting a pull request - I'll take a bit of a look into it later today.

**Comment by stp-ip** [comment]
@thomasdavis could you take a close look at it?

**Comment by drorata** [comment]
I'm also having this problem. Running `resume export myresume.pdf` doesn't yield any error. However, the resulting PDF contains simply the error message: `ERROR: No API conversion tokens available`.

**Comment by Sebastien-Meiffren** [comment]
+1

**Comment by altaf933** [comment]
+1 I also have this same issue and PDF has simply message it's **ERROR: No API conversion tokens available**.

**Comment by basiclaser** [comment]
ERROR: No API conversion tokens available :(

**Comment by caffinatedmonkey** [comment]
PDF generation is handled on the registry side. Issue: https://github.com/jsonresume/registry-server/issues/84

**Comment by thomasdavis** [comment]
PDF generation has been dropped from server support.
