### ISSUE TITLE
`resume export` attempts to make insecure connections (plain http) to various resources

### ISSUE THREAD

**Issue by magicgoose** [jsonresume/resume-cli#203]
…namely json-schema.org, jsonresume.org.
So the data received from there is susceptible to MitM attacks, which is of course bad.

Also, it doesn't work at all if these connections are blocked (or if there's no Internet connectivity altogether).

**Comment by thomasdavis** [comment]
Resume exporting is done locally now so this shouldn't be an issue.

**Comment by thomasdavis** [comment]
That being said updated all the http requests in https://github.com/jsonresume/resume-cli/commit/ed2106d9e79ead0d1241fcebd4484dc4e3069f8a

Thanks for the tip!
