### ISSUE TITLE
themes.jsonresume.org is down

### ISSUE THREAD

**Issue by techgaun** [jsonresume/resume-cli#205]
I can not seem to access themes.jsonresume.org. Instead I see an error from CloudFlare.

**Comment by howardroark** [comment]
Hmmm... Yeah this seems to make it pretty much impossible to view or generate a resume :S

**Comment by stpoa** [comment]
I've overwriten my old resume with broken one because of this :/

**Comment by thomasdavis** [comment]
Sorry that I couldn't fix this earlier and I am still waiting just a bit longer eta 2 more hours.

@stpoa Sorry to hear that, did you ever upload one to the registry that maybe I can retrieve?

**Comment by stpoa** [comment]
@thomasdavis I didn't but I have json, so no wories. Waiting for fix :)

**Comment by techgaun** [comment]
Seems to be working fine now. Thanks @thomasdavis  Am closing the issue.
