### ISSUE TITLE
Unable to use resume-cli with proxy

### ISSUE THREAD

**Issue by bsvobodny** [jsonresume/resume-cli#208]
Hi,

I'm in a corporate network and I'm using a proxy to access tjhe Internet.
I'm not able to run the following command

```
resume serve
```

or 

```
resume export [fileName]
```

In both cases, an http call is done but the address cannot be resolve, usually it's done by the proxy.

Could it be possible to add the capability to set a proxy?

Thanks,
Benjamin

**Comment by thomasdavis** [comment]
Theme exporting is done locally now. Supporting a proxy option is pretty low on the priorities at the moment.
