### ISSUE TITLE
export to pdf not functioning

### ISSUE THREAD

**Issue by basiclaser** [jsonresume/resume-cli#209]
I installed resume-cli on a new machine today
The project exports just fine to HTML, and used to export to PDF just fine on an old machine, old install of resume-cli
i get a message that the pdf is corrupted or unreadable. 
node v6.2.2 - OSX

**Comment by quadeare** [comment]
Hi,

Same problem here :/

node v0.10.46
npm 2.15.1
resume 0.4.13

![selection_003](https://cloud.githubusercontent.com/assets/3419613/16361751/a1a3523c-3b9a-11e6-9af1-63a5efff7bc6.png)

**Comment by basiclaser** [comment]
i tried with blank `resume init` JSON file too, HTML continues to work, but not PDF. I guess its an issue with a change in the PDF generating package

**Comment by quadeare** [comment]
Yes , however, this issue is known by the developement team, i have posted my issue too quickly :/

It seems that it is a duplicate of : #168

**Comment by basiclaser** [comment]
thats some great research thanks @quadeare . closing 👍
