### ISSUE TITLE
Available Skill Levels

### ISSUE THREAD

**Issue by 4fath** [jsonresume/resume-cli#213]
Hey,
where can i find any available skills level ? i just know Master then i tried Beginner it works.
But for mid levels or familiar with issues which keyword i should use ? 

Thanks

**Comment by 4fath** [comment]
I got the solutions when i try to customize .html page in the <style> tag;

 beginner , intermediate, advanced, master

**Comment by thomasdavis** [comment]
There are no limits on the keywords, see https://github.com/jsonresume/resume-schema/ to discuss schema issues.
