### ISSUE TITLE
Need to get resume.json of an already hosted resume.

### ISSUE THREAD

**Issue by VaibhavP17** [jsonresume/resume-cli#218]
Hi, 
My resume is hosted on the site (http://registry.jsonresume.org/vaibhavP17). Now I need to update my resume and hence I require the same **resume.json** file. I don't have access to my earlier resume.json. Please let me know how can I get that ?

Thanks in advance.

**Comment by thomasdavis** [comment]
Just add `.json` to the end.

http://registry.jsonresume.org/vaibhavP17.json

**Comment by VaibhavP17** [comment]
That worked. Thanks 👍

**Comment by thomasdavis** [comment]
Np
