### ISSUE TITLE
Exit code of resume test

### ISSUE THREAD

**Issue by MartijnDwars** [jsonresume/resume-cli#221]
I use a Makefile that validates the json (`resume test`). If the test fails, there is no point in exporting the resume. To the best of my knowledge, the convention is to exit with status code 0 if the test succeeded and nonzero if the test failed. Make uses a nonzero status code to terminate the build. The current solution would involve parsing the test output, but that's overkill.

If you agree this is an issue, I'd be glad to submit a patch in the upcoming days. Let me know!

**Comment by thomasdavis** [comment]
Fixed in https://github.com/jsonresume/resume-cli/commit/c3459c894e14101a17f31f9f311f89415272952d
