### ISSUE TITLE
export command doesn't ignore `--resume` option

### ISSUE THREAD

**Issue by ael-code** [jsonresume/resume-cli#225]
At the moment is not possible to specify an absolute path to the resume file while using the `export` command.

The option `--resume` is ignored while using this the `export` command.

**Comment by aegershman** [comment]
Assuming I'm reading this correctly, I've run into this recently as well. 

If I have multiple `resume.json`'s prepared for different contexts, e.g. `--resume=<employer_a>.resume.json`, it's valuable to be able to perform `resume-cli export --resume somejob-resume.json` similar to other commands like `serve`, so there isn't a hard requirement to have the file be named `resume.json` and be in the same directory as the `export` command being executed.

**Comment by thomasdavis** [comment]
Closing this in favor of #407
