### ISSUE TITLE
resume publish won't let me login

### ISSUE THREAD

**Issue by bradydowling** [jsonresume/resume-cli#228]
When I try to publish my resume, it exits out of the prompt as soon as I enter a single keystroke. This is my first time using this but I've tried hitting enter here, as well as typing in my email address, password, etc. and all seem to cause the prompt to exit immediately.

![publish](https://cloud.githubusercontent.com/assets/6668371/20783807/1ac83fa2-b74b-11e6-9493-a2101614d887.jpg)

Environment: Ubuntu 14.04 (Cloud9 IDE) with Node 4.6.1 and 6.9.1. This also happens to me on macOS with 6.9.1.

**Comment by thomasdavis** [comment]
Yep, another known bug in the middle of fixing.

do `resume login`  first

and then `resume publish` 

and choose the first option

**Comment by bradydowling** [comment]
Closing this in favor of https://github.com/jsonresume/resume-cli/issues/189
