### ISSUE TITLE
German Umlauts

### ISSUE THREAD

**Issue by proier** [jsonresume/resume-cli#23]
![jsonresume1](https://cloud.githubusercontent.com/assets/8100685/3513438/bc0d6be4-06c2-11e4-893a-ace484f01c46.png)
![jsonresume2](https://cloud.githubusercontent.com/assets/8100685/3513440/c0b025a6-06c2-11e4-9c34-3d13a43a2c92.png)

Hi

i have the problem, that the html export shows questionmarks and the pdf export shows an strange sign like chinese sign instead of german umlauts.
What is wrong?

Thank you a lot
Christian

**Comment by chrisdotcode** [comment]
This seems more like a theme/rendering issue, than an issue with the cli?

**Comment by thomasdavis** [comment]
Correct, you will have to take it up with the theme owner.
