### ISSUE TITLE
Need to delete a resume published as a guest

### ISSUE THREAD

**Issue by jannis-baratheon** [jsonresume/resume-cli#234]
I created two profiles as guest: ebf2d210 and e3c91028 (https://registry.jsonresume.org/xxxxx). I'd like them removed as one of them contains some sensitive data published by mistake.

Can you please point to how to do it?

**Comment by thomasdavis** [comment]
Deleted

**Comment by nvanh1983** [comment]
https://registry.jsonresume.org/bbaa8fad
Can you please point to how to remove it ?

**Comment by thomasdavis** [comment]
@nvanh1983 deleted =)
