### ISSUE TITLE
Feature request to have an option that prevents email obfuscation

### ISSUE THREAD

**Issue by CMCDragonkai** [jsonresume/resume-cli#237]
While this isn't a problem for HTML export, if I want to convert that to other formats, the email obfuscation becomes a problem.

I'm not sure if this is more of a problem with the themes though.

**Comment by thomasdavis** [comment]
If you self host you can avoid email obfuscation. 

Unfortunately, more people who use the hosting I believe prefer that it is obfuscated from spiders.
