### ISSUE TITLE
[Enhancement] Import from Linkedin

### ISSUE THREAD

**Issue by roccomuso** [jsonresume/resume-cli#240]
Would be worth having some feature to import data from Linkedin? perhaps as a feature on the website.

**Comment by ishu3101** [comment]
Check out https://jmperezperez.com/linkedin-to-json-resume/ which lets your export your profile from linkedin into json resume format.

**Comment by roccomuso** [comment]
Thanks @ishu3101

**Comment by thomasdavis** [comment]
The library above is the best there is for importing from linkedin.
