### ISSUE TITLE
Schema - Highlights - Sub-highlights

### ISSUE THREAD

**Issue by scirelli** [jsonresume/resume-cli#241]
Would it be possible for the highlights array to allow sub arrays?

```
 "highlights": [
      "Started the company",
      {"Built Application X":[
         "Application Highlight 1",
         "Application Highlight 2",
         ...
      ]}
    ]
```

Or some other structure to allow sub-highlights.

**Comment by thomasdavis** [comment]
All schematic suggestions should be posted on https://github.com/jsonresume/resume-schema
