### ISSUE TITLE
Consider adapting the Moya Community Continuity Guidelines for this project

### ISSUE THREAD

**Issue by einSelbst** [jsonresume/resume-cli#244]
I really like this project(s) but I've the feeling it suffers from being only relevant for a certain time for everybody (that is, until one got a new job). 

Maybe it would be helpful for the project to adapt the Moya Community Continuity Guidelines v2.0.0 found at [https://github.com/Moya/contributors](https://github.com/Moya/contributors).

A short excerpt:

> As the creators, and maintainers of this project, we want to ensure that the project lives and continues to grow. Not blocked by any singular person's computer time. One of the simplest ways of doing this is by encouraging a larger set of shallow contributors. Through this, we hope to mitigate the problems of a project that needs updates but there's no-one who has the power to do so.

> Ownership

> If you get a merged Pull Request, regardless of content (typos, code, doc fixes), then you're eligible for push access to this organization. This is checked for on pull request merges and an invite to the organization is sent via GitHub.

I just wanted to bring this to attention. It's absolutely fine to just close this issue.

**Comment by thomasdavis** [comment]
Thanks @einSelbst, have tried pretty hard to maintain a shallow ownership. Probably already have about 30 people with push access to different things. Might pass on bringing anything formal in the interim, but thanks for bringing the concept to attention.
