### ISSUE TITLE
When trying to ADD THEME after typing a letter resume quits to shell

### ISSUE THREAD

**Issue by phocks** [jsonresume/resume-cli#246]
Not sure if I'm doing something wrong or not. As soon as I start typing it just quits out.

![snip20170327_1](https://cloud.githubusercontent.com/assets/437566/24350314/13a79f66-1325-11e7-82b1-a5e5314e1a09.png)

**Comment by Kautenja** [comment]
I've been experiencing the same issue

**Comment by aodj** [comment]
I'm seeing this also with `node v7.10.0` and `npm 4.5.0`

**Comment by aodj** [comment]
This is still an issue with the latest `npm` version, `4.6.1`. Is there any way to assist in debugging to improve this issue?

**Comment by compwron** [comment]
I have this same issue. 
nvm --version # 0.33.2
npm --version # 5.3.0
resume --version # 0.4.19
