### ISSUE TITLE
Delete resume from registry

### ISSUE THREAD

**Issue by hkellaway** [jsonresume/resume-cli#247]
apologies if this isn't the correct place to put this issue - i couldn't find a specific contact.

i'd like to delete my entry from the Registry. how can i do so? i don't see a CLI command for it.

**Comment by thomasdavis** [comment]
Really bad on my part, but there is still no delete option. If you would like to email me your username or resume url I can delete it manually for you.

thomasalwyndavis@gmail.com

**Comment by thomasdavis** [comment]
Deleted!

**Comment by hkellaway** [comment]
appreciate it
