### ISSUE TITLE
Failure during installation, Please find the log here

### ISSUE THREAD

**Issue by RohanMajumdar69** [jsonresume/resume-cli#249]
7615 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:andyinabox/FileSaver.js.git C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\git-github-com-andyinabox-FileSaver-js-git-e433c213
7615 verbose stack       0 [main] git 12656 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
7615 verbose stack the public mailing list cygwin@cygwin.com
7615 verbose stack cygwin warning:
7615 verbose stack   MS-DOS style path detected: C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\git-github-com-andyinabox-FileSaver-js-git-e433c213
7615 verbose stack   Preferred POSIX equivalent is: /cygdrive/c/Users/inchunab/AppData/Roaming/npm-cache/_git-remotes/git-github-com-andyinabox-FileSaver-js-git-e433c213
7615 verbose stack   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
7615 verbose stack   Consult the user's guide for more details about POSIX paths:
7615 verbose stack     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
7615 verbose stack ssh: Could not resolve hostname github.com: Temporary failure in name resolution
7615 verbose stack fatal: The remote end hung up unexpectedly
7615 verbose stack
7615 verbose stack     at ChildProcess.exithandler (child_process.js:204:12)
7615 verbose stack     at emitTwo (events.js:106:13)
7615 verbose stack     at ChildProcess.emit (events.js:191:7)
7615 verbose stack     at maybeClose (internal/child_process.js:886:16)
7615 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
7616 verbose cwd C:\Users\inchunab\Desktop\resume-cli-master
7617 error Windows_NT 10.0.14393
7618 error argv "E:\\TOOLS\\nodejs\\node.exe" "E:\\TOOLS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--proxy=http://inchunab:#######@localhost:3135" "--proxy-https=http://inchunab:#######@localhost:3135" "--registry=http://registry.npmjs.org/" "install" "-g" "resume-cli"
7619 error node v6.10.2
7620 error npm  v3.10.10
7621 error code 128
7622 error Command failed: git -c core.longpaths=true clone --template=C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:andyinabox/FileSaver.js.git C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\git-github-com-andyinabox-FileSaver-js-git-e433c213
7622 error       0 [main] git 12656 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
7622 error the public mailing list cygwin@cygwin.com
7622 error cygwin warning:
7622 error   MS-DOS style path detected: C:\Users\inchunab\AppData\Roaming\npm-cache\_git-remotes\git-github-com-andyinabox-FileSaver-js-git-e433c213
7622 error   Preferred POSIX equivalent is: /cygdrive/c/Users/inchunab/AppData/Roaming/npm-cache/_git-remotes/git-github-com-andyinabox-FileSaver-js-git-e433c213
7622 error   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
7622 error   Consult the user's guide for more details about POSIX paths:
7622 error     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
7622 error ssh: Could not resolve hostname github.com: Temporary failure in name resolution
7622 error fatal: The remote end hung up unexpectedly
7623 error If you need help, you may report this error at:
7623 error     <https://github.com/npm/npm/issues>

**Comment by thomasdavis** [comment]
`7622 error ssh: Could not resolve hostname github.com: Temporary failure in name resolution`

This would indicate that you had a network error at the time.
