### ISSUE TITLE
Publishing using "paper" theme ignores "publications" section

### ISSUE THREAD

**Issue by stephen-kruger** [jsonresume/resume-cli#250]
When publishing a resume using the paper theme, the generated output is missing the "publications" section.

**Comment by stephen-kruger** [comment]
Publishing the same resume using "--theme classy" produces the expected section in the rendered output.

**Comment by thomasdavis** [comment]
Hey @stephen-kruger, due to the nature of how the ecosystem works, you have to take it up with the theme developer. The repo for the paper theme can be found at -> https://github.com/TimDaub/jsonresume-theme-paper
