### ISSUE TITLE
Unable to add projects section in resume

### ISSUE THREAD

**Issue by naqushab** [jsonresume/resume-cli#252]
After installing resume-cli from npm using command `npm install -g resume-cli`
I am unable to add projects section in my resume.

Also, when I checked the node_modules folder for schema.json, it doesn't not have the new schema where projects has the entry but the older one where projects and meta wasn't there.

Am I missing something?

**Comment by pyros2097** [comment]
Yep.. .I also need projects. Is there a way we can fix this?

**Comment by fluency03** [comment]
+1

**Comment by Wenzel** [comment]
Hi,

I also have this issue.
I tried the `projects` field described in the latest [schema](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json#L377)

But when generating a Resume, i have the following output :

~~~
$ resume export resume.html
Cannot export. There are errors in your resume.json schema format.

     ✗  is undefined , expected undefined

  fail  1 

Please fix your resume.json file and try again
~~~

**Comment by jmatraszek** [comment]
Hi,
as far as I understand schema currently supports projects, but I cannot get it to work in my resume. Is there a way to do this (or if it is not supported: is there a chance that this will be fixed in the cli soon)? Thanks!

**Comment by Wenzel** [comment]
hi @jmatraszek ,

I think the latest schema effectively supports the projects, but the resume-cli parser is using an old version of it.

I came up with a solution.
I wanted a resume based on the `kendall` theme:
http://themes.jsonresume.org/theme/kendall

So i forked the theme on [github](https://github.com/Wenzel/jsonresume-theme-kendall), and created a new branch to support the projects:

I modified the `index.js`: https://github.com/Wenzel/jsonresume-theme-kendall/commit/52b40179c0852f52fd7089dd90da116d772b961d

And then used the new variables in the `resume.template` file:
~~~HTML
                    {{#projectsBool}}
                    <!-- PROEJCTS -->
                    <div class="box">
                        <h2><i class= "fa fa-github-alt ico"></i> Projects</h2>
                        <ul class="list-group">
                        {{#projects}}
                        <li class="list-group-item">
                            <span style="font-weight:bold">
                                {{name}}
                            </span>
                            : {{description}}
                        </li>
                        {{/projects}}
                        </ul>
                    </div>
                    {{/projectsBool}}
~~~

Also note that I didn't followed the official JSON schema for projects.
Instead, i defined my own:

~~~JSON
    "projects": [
        {
            "name": "awesome-virtualization",
            "description": "Gathering and compiling public resources to study virtualization and enumerate commercial, open-source or research focused hypervisor projects available"
        },
        {
            "name": "windows_internals",
            "description": "Personal storage for ntdll and ntoskernel on various Windows versions to quickly study a syscall implementation"
        }
    ],
~~~

Now just install your new theme on your system:
~~~
cd jsonresume-theme-kendall
sudo npm install -g
~~~

And you can bypass the official schema validation with `-F`
~~~
resume export --theme kendall resume.html -F
Checking NPM for latest version...
Your resume-cli software is up-to-date.

Done! Find your new .html resume at:
 /home/wenzel/ownCloud/Documents/job/json-resume/resume.html
~~~

And here you go ;)
