### ISSUE TITLE
Image field URL format

### ISSUE THREAD

**Issue by Wenzel** [jsonresume/resume-cli#258]
Hi,

I would like some precisions about the `image` field.
First, the [`Schema`](https://jsonresume.org/schema/) page shows an example of `JSON` resume using a `picture` field.

However, after looking at the [schema](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json#L18) in detail, this field should be `image`. (please fix it if i'm correct).

Now, the string should be a URL pointing to a `JPEG` or `PNG` image.

I have a JPEG file in the same directory as my `resume.json`, and I tried multiple URLs:
-  `file:///full/path/to/file.jpg`
- `file://full/path/to/file.jpg`
- `/full/path/to/file.jpg`
- `file.jpg`

But none of them work.

I tested using `Kendall` and `elegant` themes. (`resume serve --theme kendall`)

Can you give an example of a working `resume.json` using the `image` field ?

Thanks !

**Comment by Wenzel** [comment]
Hi,

Any updates about this issue ?
Anyone could provide me an example of a working resume with an image ?

Thanks.

**Comment by Wenzel** [comment]
I found the issue.

I was using the command `serve`, and this doesn't use the local template, but instead relies on the server to render the resume.

So having a local file referenced with `file:///` wasn't the right solution.

I replaced it with `http://` and it works !

Thanks

**Comment by ciprian-forcos** [comment]
Issue is still present.
