### ISSUE TITLE
Install with yarn problem

### ISSUE THREAD

**Issue by fernandopasik** [jsonresume/resume-cli#263]
When installing with yarn I have the following error:

```
yarn install v1.1.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error resume-cli@0.4.19: The engine "node" is incompatible with this module. Expected version "^4".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Would it be possible to make this package allow latest node versions?

**Comment by PeterDaveHello** [comment]
We can use `>=4` in the package.json, but should also bump the versions in the other related packages, PRs are welcome :)

**Comment by fernandopasik** [comment]
Awesome! @PeterDaveHello I'll work on a PR for that.

**Comment by fernandopasik** [comment]
@PeterDaveHello after some digging I found out that we need to update html-to-text as it has as well an issue with the node compatibility.

In the repo https://github.com/jsonresume/resumeToText/ there's a pull request that is doing that:
https://github.com/jsonresume/resumeToText/pull/6

**Comment by PeterDaveHello** [comment]
@fernandopasik yes you are right, I just added that service which will take care of npm dependency! You can still help bump all the nodejs engine version requirement in all the modules :)

**Comment by fernandopasik** [comment]
@PeterDaveHello yes, I will, but that module we need first.

**Comment by PeterDaveHello** [comment]
It's done now.

**Comment by fernandopasik** [comment]
I think you are still missing a new release of https://github.com/jsonresume/resumeToText

**Comment by brendaniel** [comment]
use *--ignore-engines* flag 👍

**Comment by PeterDaveHello** [comment]
@fernandopasik I have no permission, @brendaniel 's comment could be useful.

Ping @thomasdavis to update the npm module, thanks!
