### ISSUE TITLE
resume.html contains style only

### ISSUE THREAD

**Issue by kaspermarstal** [jsonresume/resume-cli#271]
Hi, 

When running `resume export resume.html` with version 0.4.19 on macOS Sierra, an html with style info is generated. The actual content is missing. This is the output:

	<!doctype html>
	<html>
	<head>
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, minimal-ui">
	
	<title></title>
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/2.0.2/octicons.min.css">
	
	<style type="text/css">
	@import url(
	https://fonts.googleapis.com/css?family=Lato:400,700
	);
	body {
		background: #fff;
		font-family: Lato, sans-serif;
		margin: 0 0 80px;
	}
	a {
		color: #2ecc71;
	}
	a:focus,
	a:hover {
		color: #f1c40f;
		text-decoration: none;
	}
	p {
		line-height: 1.5;
		margin: 0;
	}
	p + p {
		margin-top: 10px;
	}
	h1,
	h2,
	h3,
	h4 {
		margin-top: 0
	}
	section {
		margin-top: 30px;
	}
	li {
		line-height: 1.8;
		list-style: none;
	}
	li:before {
		content: "\f052";
		float: left;
		font: 13px Octicons;
		margin-top: 6px;
		margin-left: -20px;
		opacity: .1;
		position: absolute;
	}
	blockquote {
		border-left: 5px solid #e7e9ec;
		font-size: 14px;
	}
	em {
		color: #95a5a6;
		font-weight: normal;
		font-style: normal;
	}
	h4 span:first-child {
		color: #000;
		font-weight: bold;
	}
	.container {
		max-width: 750px;
		padding: 0 30px;
	}
	.col-sm-6 {
		margin-bottom: 10px;
	}
	.col-sm-12 h4 {
		margin-top: 12px; 
	}
	.col-sm-12 + .col-sm-12 {
		margin-top: 30px;
	}
	#header {
		background: #f4f6f6;
		padding: 50px 0;
		margin-bottom: 30px;
	}
	#header h2 {
		color: #95a5a6;
		font-size: 24px;
	}
	#content h3 {
		color: #f1c40f;
		font-size: 26px;
		margin-top: -4px;
	}
	#content aside {
		text-align: right;
		padding-right: 30px;
	}
	#profiles .network {
		text-transform: capitalize;
	}
	#work .position,
	#volunteer .position {
		font-weight: bold;
		margin-bottom: 8px;
	}
	#education .area {
		font-weight: bold;
	}
	#education .area:before {
		content: "\f0d7";
		font: 16px Octicons;
		margin-right: 6px;
	}
	#education .studyType {
		margin-left: 25px;
	}
	#awards .summary,
	#publications .summary {
		margin-top: 8px;
	}
	#publications .website a:before {
		content: attr(href);
	}

	@media (min-width: 480px) {
		.strike-through {
			border-top: 1px solid #f4f6f6;
			height: 20px;
			margin-top: 12px;
			margin-bottom: -2px;
			position: relative;
		}
		.strike-through span,
		.strike-through a {
			background: #fff;
			position: absolute;
		}
		.strike-through span:first-child {
			padding-right: 20px;
			margin-top: -12px;
		}
		.strike-through span + span {
			font-size: 14px;
			margin-top: -10px;
			padding-left: 20px;
			right: 0;
		}
	}
	@media (max-width: 768px) {
		.col-sm-6:last-child {
			margin-bottom: 0px;
		}
		#content aside {
			margin-bottom: 20px;
			padding-right: 0;
			text-align: left;
		}
		#publications .website a:before {
			content: "View publication";
		}
	}
	@media (max-width: 480px) {
		h1 {
			font-size: 26px;
		}
		.date {
			font-size: 14px;
			margin-bottom: 5px;
		}
		.strike-through span:first-child {
			margin-bottom: 7px;
		}
		.strike-through span {
			display: block;
		}	
		#header {
			margin-bottom: 10px;
			padding: 40px 0;
		}
		#actions {
			display: none;
		}
	}

		</style>
		
		</head>
		<body>
		
		<header id="header">
			<div class="container">
				<div class="row">
					<div class="col-sm-9 col-sm-push-3">
					</div>
				</div>
			</div>
		</header>
		<div id="content" class="container">

		</div>
		
		</body>
	</html>

**Comment by ahamid** [comment]
Same here on Fedora Linux 30.

**Comment by thomasdavis** [comment]
For anyone encountering this problem now, please either share your resume.json or make sure it is valid first.

**Comment by thomasdavis** [comment]
Continued in #392
