### ISSUE TITLE
Publishing to private Domain name

### ISSUE THREAD

**Issue by shapan1** [jsonresume/resume-cli#272]
Currently, I have published my json resume to https://registry.jsonresume.org/sdashore. However, I want to publish this to my Namecheap domain. Can anyone please guide me!

**Comment by moribellamy** [comment]
The HTML generated by `resume export foo.html` seems to be self-contained, so you could just drop it into whatever hosting provider you are using behind namecheap's DNS.

**Comment by frg** [comment]
Seems like this can be closed @PeterDaveHello

**Comment by thomasdavis** [comment]
Custom domains are only supported via self hosting.
