### ISSUE TITLE
Slick theme CSS problem

### ISSUE THREAD

**Issue by lenguyenthedat** [jsonresume/resume-cli#274]
Hey guys, not sure if it's the right place to post issue regarding the themes, but there is a CSS problem with this theme: http://registry.jsonresume.org/#slick

**Comment by frg** [comment]
![image](https://user-images.githubusercontent.com/1245426/37342995-82090476-26c6-11e8-9d49-7ed75a8f1669.png)

Seems like this link is a 404. Should replace with `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css`

**Comment by antialias** [comment]
We can close this one as it is irrelevant to the resume-cli codebase.

@lenguyenthedat this issue is tracked on the slick theme repo: https://github.com/dfmcphee/jsonresume-theme-slick/issues/7
