### ISSUE TITLE
OSX - Install of Resume-Cli gives error on phantomjs

### ISSUE THREAD

**Issue by jessequinn** [jsonresume/resume-cli#276]
Jesses-iMac-2:new jessequinn$ sudo npm install -g resume-cli
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
/opt/local/bin/resume -> /opt/local/lib/node_modules/resume-cli/index.js

> phantomjs-prebuilt@2.1.16 install /opt/local/lib/node_modules/resume-cli/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /opt/local/lib/node_modules/resume-cli/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1519818744524/phantomjs-2.1.1-macosx -> /opt/local/lib/node_modules/resume-cli/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /opt/local/lib/node_modules/resume-cli/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 (node_modules/resume-cli/node_modules/phantomjs-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by keremcankabadayi** [comment]
same here!

`10.13.2 Beta (17C79a)`

**Comment by NoobTW** [comment]
same here

**Comment by keremcankabadayi** [comment]
I just got over this issue.

```
git clone https://github.com/jsonresume/resume-cli.git
cd resume-cli
sudo npm install
```

after the modules installations done, you can use `node index.js [command] [options]`. I'm using `stackoverflow` theme now, it works. PDF export doesn't work properly but you can use `.html` and export some other node.js repos.
