### ISSUE TITLE
Can't publish with password access?

### ISSUE THREAD

**Issue by lubekpl** [jsonresume/resume-cli#277]
Resume version: 0.4.19
Node version: 9.4.0

While trying to publish my resume (which was/still is available publicly), I've tried to publish it to my account with a password protection. Unfortunately after trying to input anything, resume-cli crashes without any errors. I'm registered and am logged in.

<img width="497" alt="screen shot 2018-03-01 at 15 16 47" src="https://user-images.githubusercontent.com/1672262/36849352-1bac9546-1d64-11e8-89a0-b36ee12027d8.png">

**Comment by mqzry** [comment]
Same for me

**Comment by NAlexPear** [comment]
The same happened to me, but I managed to get around this issue in the meantime with `resume login` followed by the `Publish to your account` option of `resume publish`

**Comment by mqzry** [comment]
That is not the same as publishing to your account with password access. The resume will be not be publicly accessible then.
