### ISSUE TITLE
Is this tool dead?

### ISSUE THREAD

**Issue by frg** [jsonresume/resume-cli#278]
Is this tool dead?

Seems like the community wants to support it (56 issues, 13 pull requests) yet they haven't been interacted with by the official maintainers for a while.

I would gladly help out clearing out some of the backlog if need be. @PeterDaveHello

**Comment by cube5** [comment]
Totally agree, this is a great project I would love to know if is still mantained or not and how can we help.

**Comment by frg** [comment]
@cube5 and anyone that's interested in a tool similar to this I found another tool on Github which seems to be supported better over here https://github.com/hacksalot/HackMyResume.

I'm currently using this instead and it even supports resume-schema & its themes!

**Comment by PeterDaveHello** [comment]
Sorry for the late reply, I think I and @thomasdavis are both too busy to take good care of this project right now, really appreciate anyone who wants to get involved, there are many issues need to be solved.

**Comment by frg** [comment]
@PeterDaveHello Yeah, I know how that feels. Hope I didn't come off as arrogant by suggesting another tool on here.

Anyway, great project though! 👍
