### ISSUE TITLE
NPM Version outdated

### ISSUE THREAD

**Issue by scarby** [jsonresume/resume-cli#288]
The version of this project stored in NPM is outdated (and the PhantomJS problems make it rather difficult to install)

Are you able to push a new version of the package?

Thanks

**Comment by mltbnz** [comment]
Same problem here. I want to delete my online resume but I have to install the client first as it looks

**Comment by scarby** [comment]
@mltbnz The master branch of this repo works. You can install it with npm install -g https://github.com/jsonresume/resume-cli/

The changes from here were never released to npm
