### ISSUE TITLE
pdf export removed in `1.0.1` but was working on `master`

### ISSUE THREAD

**Issue by MarcLoupias** [jsonresume/resume-cli#291]
Hello,

pdf export was removed with [this commit](https://github.com/jsonresume/resume-cli/commit/7d5f8a7fb3681865e0c7f5b88e462988c0475f2d) but ... It was working !

The #275 PR makes it working very well. It was merged in `master` but not released in npm registry.

Could you (@thomasdavis ) revert your last change to enable again pdf export please ?

Or maybe i have missed something ?

**Comment by randytarampi** [comment]
I'd also like to shill the work I did in #282 and #283 to get it flexible enough for [`jsonresume-theme-randytarampi`](https://www.npmjs.com/package/jsonresume-theme-randytarampi) to print on [A4](https://github.com/randytarampi/me.resume/blob/master/a4.pdf), [US Letter](https://github.com/randytarampi/me.resume/blob/master/letter.pdf) and [US Legal](https://github.com/randytarampi/me.resume/blob/master/legal.pdf).

Would be super nice to see PDF support come back in the 1.x line.

**Comment by MarcLoupias** [comment]
The new `1.1.1` `resume-cli` version enable pdf export but it ignore the `--theme` parameter.

It was possible to use `resume-cli` and another theme into a node project to export a pdf with the theme added in deps.

No it takes the default theme and ignore the given one.

For example, this CLI command : 

```bash
npx -p node@latest -- node node_modules/.bin/resume export dist/cv.pdf --format pdf --theme developpez
```

Gave before a pdf with the `developpez` theme. Now it gives the pdf with the default theme (the `flat` one i guess).

**Comment by thomasdavis** [comment]
Thanks for the patience guys. I was originally of the mind that no one was using it for pdfs much, but I can see the need for it now. Can't but help love the puppeteer magic too. 

@randytarampi Superb PR's, will be your next ones quicker.

I've published the merged changes under `1.1.2`

And invited both of you to have commit access.

**Comment by jphellemons** [comment]
I have 1.1.2 according to `npm list -g --depth=0` but when I run `resume export --format pdf` in the dir where my resume.json is, I get an empty PDF file. `resume export --format html resume.html` does work perfectly and generates a valid file. The 1kb pdf does contain some data:

    %PDF-1.4
    %Óëéá
    1 0 obj
    <</Creator (Chromium)
    /Producer (Skia/PDF m72)
    /CreationDate (D:20190102145814+00'00')
    /ModDate (D:20190102145814+00'00')>>
    endobj
    2 0 obj
    <</Filter /FlateDecode
    /Length 95>> stream
    xœÓ32¶ ÔÕCâš[)$çrrdŒLM
    Œ
    ŠR¹Âµò€âÆz†F¦`}Pƒ¡¹+@Eé\úî
    éÅ`s,Í
    LÍ@Æ¤q! œÙø
    endstream
    endobj
    3 0 obj
    <</Type /Catalog
    /Pages 4 0 R>>
    endobj
    4 0 obj
    <</Type /Pages
    /Count 1
    /Kids [5 0 R]
    /Resources <</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]>>>>
    endobj
    5 0 obj
    <</Type /Page
    /Resources <</ExtGState <</G0 6 0 R>>>>
    /MediaBox [0 0 612 792]
    /Contents 2 0 R
    /StructParents 0
    /Parent 4 0 R>>
    endobj
    6 0 obj
    <</ca 1
    /BM /Normal>>
    endobj
    xref
    0 7
    0000000000 65535 f 
    0000000015 00000 n 
    0000000154 00000 n 
    0000000318 00000 n 
    0000000365 00000 n 
    0000000481 00000 n 
    0000000623 00000 n 
    trailer
    <</Size 7
    /Root 3 0 R
    /Info 1 0 R>>
    startxref
    660
    %%EOF

**Comment by MarcLoupias** [comment]
It works for me in 1.1.2 with any custom theme.

**Comment by jphellemons** [comment]
Does it use puppeteer or the Skia export? How should I troubleshoot this properly?

**Comment by MarcLoupias** [comment]
Puppeteer. Seems you don't fulfill a theme option in your command line, try using one.

**Comment by jphellemons** [comment]
I ran it from a theme dir. The html output does use the theme from the dir.

**Comment by jphellemons** [comment]
Running `resume export resume.pdf -f pdf -t flat` also gives me a 1kb pdf file with the same content as I posted before.

**Comment by hannodrefke** [comment]
I have exactly the same issue, using Ubuntu Linux.
`resume export resume.pdf -f pdf -t flat` generates a PDF file with one blank page.

**Comment by randytarampi** [comment]
Hm – this should be fixed by #294.

@hannodrefke @jphellemons Can you try using https://github.com/jsonresume/resume-cli/pull/294?

Was hoping that someone would verify that fixed the issue for them before asking someone to merge it in.

**Comment by hannodrefke** [comment]
> Was hoping that someone would verify that fixed the issue for them before asking someone to merge it in.

Sorry for the late response - it works with these steps:
https://github.com/jsonresume/resume-cli/pull/294#issuecomment-451366924

Thank you!

**Comment by Tasemu** [comment]
I'm trying to export my resume using the following:

`resume export resume.pdf -f pdf -t flat -F`

the resume is created but is totally blank

**Comment by Tasemu** [comment]
> @Tasemu have you tried the steps in [#294 (comment)](https://github.com/jsonresume/resume-cli/pull/294#issuecomment-451366924)?

I have, but the branch appears to not exist

**Comment by Tasemu** [comment]
@randytarampi Sorry to bug you man, if the branch doesn't exist, is there another option I can go with?

**Comment by hannodrefke** [comment]
@Tasemu Where exactly do you have problems?

This solution by @randytarampi worked for me:

`# Set things up
git clone git+ssh://github.com/randytarampi/resume-cli.git
cd resume-cli
git checkout puppeteer-v1.11.0
npm install

# Copy over your `resume.json` here...
# cp ../me/packages/jsonresume-theme/resume.json .

# Generate a `resume.pdf` using `jsonresume-theme-flat` 
./index.js export resume.pdf --force -f pdf --theme flat

# Generate a PDF using a custom theme, like `jsonresume-theme-elegant`
npm install jsonresume-theme-elegant
./index.js export resume.pdf --force -f pdf --theme elegant`

**Comment by Tasemu** [comment]
@hannodrefke Hi mate, i run into issues with this step here:

`git checkout puppeteer-v1.11.0`

It appears this branch does not exist on the resume-cli git repository so cannot be checked out

**Comment by hannodrefke** [comment]
@Tasemu that is strange, it does exist:

` * [puppeteer-v1.11.0] fix(export): Adjust `createPdf` for the `puppeteer^1.11.0` API.`

You can list all existing branches with `git show-branch -a`.

---

I just cloned the repo:
`git clone http://github.com/randytarampi/resume-cli.git` 
moved inside the directory:
`cd resume-cli`
and then switched to the branch:
`git checkout puppeteer-v1.11.0`

And it worked as expected.

Please make sure you have pulled the latest changes with `git pull`.

**Comment by Tasemu** [comment]
Ah, i have cloned the official repository. Is this one a fork? oops

**Comment by wmedali** [comment]
problem still reproduced in master
the pdf export command created a pdf with blank page each time
