### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by rfabro** [jsonresume/resume-cli#295]
Tried to login and I got a Bad Gateway response. My url is also inaccessible, seems like the server is down

![image](https://user-images.githubusercontent.com/11796900/50228889-030b2680-03e4-11e9-9648-7bcd7be6bdae.png)

**Comment by ErikMuir** [comment]
This is still an issue.

**Comment by heylookltsme** [comment]
I'm seeing what I'm assuming is a related issue when trying to serve a resume locally - 
```

**Comment by heylookltsme** [comment]
Also this - 
<img width="1278" alt="themes_jsonresume_org___522__connection_timed_out" src="https://user-images.githubusercontent.com/1299305/50384779-9ddf5b80-0697-11e9-89e2-c1b7d2a38f6c.png">

**Comment by rfabro** [comment]
Got this error and connection timed out when viewing my page. 
![image](https://user-images.githubusercontent.com/11796900/50397397-2dc1fa00-07ab-11e9-9032-b7b6976f7bd4.png)

**Comment by rfabro** [comment]
Got this error and a connection timed out error when viewing my page:
![image](https://user-images.githubusercontent.com/11796900/50397418-5518c700-07ab-11e9-990f-b529f59ff808.png)

**Comment by alistaircom** [comment]
Getting the same error:

```
Requesting theme from server...
There was an error downloading your generated html resume from our server: Error: Unsuccessful HTTP response
```

**Comment by VaibhavP17** [comment]
Is there a workaround ? I am stuck because of this, need to apply for some jobs after updating the CV.

**Comment by rfabro** [comment]
> Is there a workaround ? I am stuck because of this, need to apply for some jobs after updating the CV.

Update your json file then export your resume in html format.

**Comment by VaibhavP17** [comment]
Thanks a lot @rfabro . Worked like a charm today. I only had to download one theme module and run the command from inside it. (y)

**Comment by rajudev** [comment]
will the server get back again sometime? or is the service dead now?

**Comment by JohnJohnstone** [comment]
If the project is going to rely on a server by default when using the instructions provided it may be a good idea to leat users know in the readme that your server is down when that occurs. As it stands there are currently broken links on your website, and the getting started guide fails to generate a resume at all becasue it is trying to download themes.

**Comment by tuxfanou** [comment]
Project seems to be dead, it's impossible to download theme, so impossible to generate resume.

**Comment by kovalevivan** [comment]
> Project seems to be dead, it's impossible to download theme, so impossible to generate resume.

You can download theme from here https://www.npmjs.com/search?q=jsonresume-theme-*

**Comment by tuxfanou** [comment]
It works like a charm.
Thank you so much :)

**Comment by rajudev** [comment]
> > Project seems to be dead, it's impossible to download theme, so impossible to generate resume.
> 
> You can download theme from here https://www.npmjs.com/search?q=jsonresume-theme-*

Could you guess tell me how to use the themes there precisely. 

I tried installing the theme via npm and then tried using them with `resume serve --theme <themename>` . It did not work as expected.


How are you people doing it?

**Comment by rfabro** [comment]
> > > Project seems to be dead, it's impossible to download theme, so impossible to generate resume.
> > 
> > 
> > You can download theme from here https://www.npmjs.com/search?q=jsonresume-theme-*
> 
> Could you guess tell me how to use the themes there precisely.
> 
> I tried installing the theme via npm and then tried using them with `resume serve --theme <themename>` . It did not work as expected.
> 
> How are you people doing it?

What error message do you encounter? Using the `resume serve --theme <themename>` works just fine for me. Better if you just follow the [hosting steps](https://jsonresume.org/getting-started/) by creating a gist and pasting your JSON there while including the following code:  
```
"meta": {
    "theme": "<your theme here>"
  }
```

**Comment by rfabro** [comment]
Will be closing as the CLI is now working for a [new registry infrastructure was implemented](https://github.com/jsonresume/registry-server/issues/105).
