### ISSUE TITLE
resume serve shows local theme, but resume export shows 'flat'

### ISSUE THREAD

**Issue by jeanpoelie** [jsonresume/resume-cli#298]
When I run `resume serve` I see my self designed resume with styling and everything, 
but as soon as i run `resume export` it will show me the flat version, both in .html and .pdf.

**Comment by jeanpoelie** [comment]
Yes I am indeed, when i add the `foo` paramater the following is my error messages:

```
To publish your resume at https://jsonresume.org type the command resume publish
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\Users\bar\Documents\GitHub\node_modules_test\resume-cli\node_modules\puppeteer\lib\FrameManager.js:1276:21)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\bar\Documents\GitHub\node_modules_test\resume-cli\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.setContent (C:\Users\bar\Documents\GitHub\node_modules_test\resume-cli\node_modules\puppeteer\lib\Page.js:615:42)
    at Page.<anonymous> (C:\Users\bar\Documents\GitHub\node_modules_test\resume-cli\node_modules\puppeteer\lib\helper.js:145:23)
    at C:\Users\bar\Documents\GitHub\node_modules_test\resume-cli\lib\export-resume\index.js:105:16
    at process.internalTickCallback (internal/process/next_tick.js:77:7) name: 'TimeoutError' } '`createPdf` errored out'

Done! Find your new .pdf resume at:
 C:\Users\bar\Documents\GitHub\jsonresume-theme-partech\resume.pdf
```

**Comment by siddharthst** [comment]
Same problem. Simply `git clone <customtheme>` and then using it is not possible. I can see it using serve but not really export it.

**Comment by sambP** [comment]
Why is the export command not using my local theme? How could I use my local theme without to publish it?

Even after I published it to the npm registry, it is not possible to use it. I get this error: Theme not supported please visit -> https://github.com/jsonresume/theme-functions/issues/12

**Comment by sambP** [comment]
@randytarampi why should he pass a theme? It should simple use the local theme. Exact like the serve command.

**Comment by rocketspacer** [comment]
Can we allow "." as theme name so it can be `require('.')` as a local theme package during development @thomasdavis 
https://github.com/jsonresume/resume-cli/blob/master/lib/export-resume/index.js#L17
```js
var theme = program.theme;
if (!theme.match('jsonresume-theme-.*') && theme != '.'){
    theme = 'jsonresume-theme-' + theme;
}
```

**Comment by thomasdavis** [comment]
@rocketspacer If you run `resume serve` in your local theme folder it should serve it up, let me know if it doesn't

**Comment by thomasdavis** [comment]
I will on getting rendering local theme folders working.

**Comment by RomRider** [comment]
Is that already in place for this issue to be closed?

**Comment by thomasdavis** [comment]
Sorry I forgot to link the other issues relating to it. 

But I just pushed up `2.1.1` which now allows as you suggested for `--theme .` or `-theme ../some/other/dir` 

Thanks for the patience
