### ISSUE TITLE
Theme specific configurations

### ISSUE THREAD

**Issue by remydagostino** [jsonresume/resume-cli#30]
Resume themes are only given the data from the resume to work with.

It would be cool if there could be a standard way to pull-in user defined configuration options for a theme. Without that, the only way to make small customisations to a theme would be to fork the repo and I think that would lead to things like `theme-modern`, `theme-modern-dark`, `theme-modern-dark-futura' etc etc.

Would it be possible to have the theme manager automatically include a `.css` file with the same name as the theme if it exists in the directory that the command is run in? I'm not sure if this is a workable idea but it does seem like a problem that there is no standard way to pass extra theme-formatting specific data into a theme.

**Comment by thomasdavis** [comment]
Specific theme config can be done in the `meta` tag of the schema but try to avoid it where you can.
