### ISSUE TITLE
Exporting to doc, docx strategy

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-cli#31]
(strategy goes here)

No real idea just yet, investigating PanDoc (http://johnmacfarlane.net/pandoc/)

**Comment by jorgeas80** [comment]
Not sure if the project is still alive, but I use Docxtemplater for docx handling in NodeJS --> https://docxtemplater.com/

Do let me know if you need more info about this topic

**Comment by thomasdavis** [comment]
What @jorgeas80 posted looks cool, but we haven't had much interest in doc formats for a while so closing this issue.

**Comment by caffeinatedMike** [comment]
@thomasdavis I think this is worth a revisit because recruiters will often ask for a copy of a resume in the form of a word doc (docx). So, this would really come in handy.
