### ISSUE TITLE
Latest version (1.2.4) yields errors when ran

### ISSUE THREAD

**Issue by brandonb927** [jsonresume/resume-cli#331]
Running the latest version (1.2.4) of resume-cli yield an error while attempting to export:

```
resume-cli/lib/test.js:40
  errors.errors.forEach(function(error) {
                ^

TypeError: Cannot read property 'forEach' of undefined
    at errorFormatter (.../lib/node_modules/resume-cli/lib/test.js:40:17)
    at .../lib/node_modules/resume-cli/lib/test.js:73:7
    at callbackWrapper (.../lib/node_modules/resume-cli/node_modules/resume-schema/validator.js:17:7)
    at .../lib/node_modules/resume-cli/node_modules/z-schema/src/Report.js:46:13
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

This appears to be related to the most [recent commit](https://github.com/jsonresume/resume-cli/commit/0fed1e2a7b1c897c5adf19e3ecd1d106b5389e24#diff-dd2e881af3311f834199c7b515cff0c7R60) which may have accidentally reverted a change from [this commit](https://github.com/jsonresume/resume-cli/commit/699c804f97e9c14487fe372d61086617a9ef074f).

**Comment by juangburgos** [comment]
Got same error here

**Comment by doomcrewinc** [comment]
I'm getting the same error as well.

**Comment by Pomettini** [comment]
I'm having the same error

**Comment by rfabro** [comment]
Had encountered this error as well when running `resume test`. Though my resume is served just fine.

**Comment by bh-adrienne** [comment]
The test code wasn't following the right error format. I've submitted a PR. https://github.com/jsonresume/resume-cli/pull/336
