### ISSUE TITLE
"ERROR: Failed to download Chromium" when trying to install with npm

### ISSUE THREAD

**Issue by dolphingarlic** [jsonresume/resume-cli#334]
When I try to install resume-cli with the command `sudo npm install -g resume-cli`, I get the following error:

```
ERROR: Failed to download Chromium r674921! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.19.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.19.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

What is going wrong here? My node version is v11.14.0 and my npm version is 6.7.0

**Comment by OmriSama** [comment]
Also having this issue

**Comment by OmriSama** [comment]
So it turns out the issue is installing Puppeteer globally which is (for some reason) a dependency of `resume-cli`. 

I was able to install both Puppeteer and Resume using these commands:

```shell
$ sudo npm install puppeteer --unsafe-perm=true --allow-root
$ sudo npm install resume-cli --unsafe-perm=true --allow-root
```

Whether you actually want to use those flags or not is a different story.

I'm on the latest Node/npmwith Ubuntu 19.04.

**Comment by TechQuery** [comment]
Users in some countries (such as People Republic of China) can't access **the download server of Chromium**...

**Using local Chrome** (with [`puppeteer-core`](https://www.npmjs.com/package/puppeteer-core)) may be a better solution, I can make a pull request to do this.

**Comment by aleifuu** [comment]
same issue here. I don't think it's about not able accessing download server of Chromium or wether you are in China 

(xenial)pi@localhost:~/resume-cli.old$ node -v
v10.16.0
(xenial)pi@localhost:~/resume-cli.old$ npm -v
6.10.3

I was about to 'upgrade' the resume executable, but now is gone ... please help solving this chromium dependency

**Comment by shadabk96** [comment]
Hi, Can this issue be taken up on priority? It's really embarrassing if the install command itself is throwing errors.

**Comment by shadabk96** [comment]
Turns out there was another issue from my end as well with multiple node versions conflicting. After I cleaned that all up, I was able to install using `npm install -g resume-cli`

P.S.: Ensure you do not use `sudo` if you've installed node/npm using nvm
