### ISSUE TITLE
Why is v1.2.7 on npm but releases here on github are 0.4.14?

### ISSUE THREAD

**Issue by gh0st** [jsonresume/resume-cli#341]
Any particular reason why we're only seeing tags/releases up to version [0.4.14 here on github](https://github.com/jsonresume/resume-cli/releases) and [version 1.2.7 on npm](https://www.npmjs.com/package/resume-cli)?

**Comment by rbardini** [comment]
Version tags have been back-filled as part of #359, closing this.
