### ISSUE TITLE
init-resume.json doesn't match the schema

### ISSUE THREAD

**Issue by evanplaice** [jsonresume/resume-cli#347]
The `init-resume.json` file used during `resume-cli init` doesn't match the schema. Various fields are misnamed, and both the `projects` and `meta` sections are missing.

**Comment by evanplaice** [comment]
Pivoting to a better approach. The CLI should pull the example direct from `resume-schema` so it never falls out-of-sync with the schema.

**Comment by thomasdavis** [comment]
Fixed sometime this year.
