### ISSUE TITLE
Not possible to install as instructions say

### ISSUE THREAD

**Issue by dcantatore** [jsonresume/resume-cli#365]
Getting the cli installed globally is not a very straight forward process at all, and it appears to be outdated. When I created a resume with this service 3 years ago it worked but I went in to update it today on another computer and I can't even get the cli going.

One can't simple install globally with so many dependencies on versions etc.  Is there a method to run it in a directory as if it's part of a project?

I'm stuck trying to figure out now what I should do without polluting my global installs.'

Has anyone else figured out how to work around this?

**Comment by thomasdavis** [comment]
Hey @dcantatore so you are installing via `npm i -g resume-cli`?

**Comment by dcantatore** [comment]
Yes
On 6/24/2020 7:52:04 AM, Thomas Davis <notifications@github.com> wrote:
Hey @dcantatore [https://github.com/dcantatore] so you are installing via npm i -g resume-cli?

**Comment by thomasdavis** [comment]
Ahh okay. 

What error did you get on your other machine?

**Comment by dcantatore** [comment]
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
/usr/local/bin/resume -> /usr/local/lib/node_modules/resume-cli/index.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/resume-cli/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/.local-chromium'
}
npm WARN notsup Unsupported engine for html-to-text@0.0.8: wanted: {"node":"~0.8.0"} (current: {"node":"13.12.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: html-to-text@0.0.8

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by thomasdavis** [comment]
I will have to take a look tomorrow, I assume it didn't work on Linux for you? 

Just FYI, we did release an easiest hosting mechanism -> https://jsonresume.org/getting-started/

**Comment by dcantatore** [comment]
I know this project is far along it's path and not likely to change but have you ever considered using something like pdfkit package to create the pdfs. I imagine that's the more complicated part of html vs pdf creation.  I use it with great ease and success on an e-commerce site to generate shipping /invoice labels with lots of different builds.

**Comment by geeeedev** [comment]
I'm having the same issue.  I installed with **sudo** prefix due to my machine setting: `sudo npm install -g resume-cli`
But in the end I still got the same error as dcantatore posted 8 days ago:

npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
/usr/local/bin/resume -> /usr/local/lib/node_modules/resume-cli/index.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/resume-cli/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/.local-chromium'
}
npm WARN notsup Unsupported engine for html-to-text@0.0.8: wanted: {"node":"~0.8.0"} (current: {"node":"12.16.3","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: html-to-text@0.0.8

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tyutyutyu** [comment]
Related to [npm install -g puppeteer fails #375](https://github.com/puppeteer/puppeteer/issues/375).

Try to install via `sudo npm install -g resume-cli --unsafe-perm=true`

**Comment by dcantatore** [comment]
sudo npm wasn't the answer in the end, because the dependencies will still be block from installing such as chromium.

you need to follow this guide:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by thomasdavis** [comment]
Thanks guys. I'm really starting to think we should remove pdf export forever, it causes way to many issues cross platform. 

People can generate html and figure out how to convert that html to pdf themselves. (with recommend suggestions)
