### ISSUE TITLE
Move .jsonresume.json to XDG path

### ISSUE THREAD

**Issue by strogiyotec** [jsonresume/resume-cli#380]
Good day, I read documentation and didn't find a clue about it . My problem is that cli creates **.jsonresume.json** file in home directory. I follow XDG specification and all my config files are stored in `~/.config` path, is it possible to move this file to another folder using environment variables or passing argument to resume cli ? 
Thank you in advance

**Comment by thomasdavis** [comment]
It is not possible sorry, but I am considering removing the configuration file as it is only used for checking the version of the tool.
