### ISSUE TITLE
Possibility to add custom object names (other than what jsonresume schema allows)?

### ISSUE THREAD

**Issue by mazgajmaciek** [jsonresume/resume-cli#383]
I do apologize if I am missing something but what I would like to do is to add a custom provision / clause that's usually required on a resume by recruiters (GDPR kind of thing). Just like you can use objects like "basics" or "work", I would like to add my custom e.g. named "provision" to add this required clause. As a work-around I am using "references" object but it's not exactly what I want. 
Is this possible somehow?

**Comment by thomasdavis** [comment]
The schema is restrictive by nature and works off the idea of innovation through constraints. 

But it is flexible the sense that you can fork or build your own theme, and then rely on the top level property called `meta` which let's you specify what ever you want.
