### ISSUE TITLE
Serving local themes is broken

### ISSUE THREAD

**Issue by XuluWarrior** [jsonresume/resume-cli#386]
https://github.com/jsonresume/resume-cli/commit/5be2b49a413374bc4df81f8c7bad3ef1f4eb53b2 removed the default behaviour of `resume serve` to look for `index.js` to use as theme.

The current documentation still states that 
`If no theme is specified, it will look for the file index.js and call render(). This is useful when developing themes."`
So I assume that removing this behaviour was unintended.

**Comment by rbardini** [comment]
Indeed it was not the intention to break this feature. For a possible workaround, have a look at https://github.com/jsonresume/resume-cli/pull/360#issuecomment-681168984.

**Comment by XuluWarrior** [comment]
Thanks for the quick response.
For know I'm happy to just pin the version at 1.2.8.  It is only used in my CI to render the local theme for Percy snapshots.

**Comment by dahlke** [comment]
Pinning has solved the issue for me as a temporary workaround, but due to all the old dependencies in 1.2.8, including it in a repo causes GitHub's dependabot to throw all sorts of alerts, so definitely something I personally would like to see resolved! Lmk if y'all want help on a PR.

**Comment by thomasdavis** [comment]
Will get this one working asap.

**Comment by thomasdavis** [comment]
I just pushed up 2.1.1 which now allows as you suggested for --theme . or -theme ../some/other/dir

Thanks for the patience

**Comment by dahlke** [comment]
Thank ya!
