### ISSUE TITLE
Any service that does PDF generation? Free or paid

### ISSUE THREAD

**Issue by DustinWehr** [jsonresume/resume-cli#389]
I've never managed to get PDF generation through resume-cli working, having spent hours trying on Linux, Windows, and OSX. Using browsers' print-to-pdf feature always messes it up in some way. 

I was last using a modified Kendall theme, but I'm open to anything that looks OK in PDF form.

Is there any, possibly paid, service that I can use to generate a PDF version of https://registry.jsonresume.org/dustinwehr ? That's with the unmodified Kendall theme, which doesn't show my references' names, but I'm kind of desperate so...

**Comment by thomasdavis** [comment]
I just load chrome and print to pdf

**Comment by DustinWehr** [comment]
@thomasdavis as I said: Using browsers' print-to-pdf feature always messes it up in some way.

**Comment by randytarampi** [comment]
You don't really have too many great, sure-fire options other than [rolling your own theme like me](https://www.npmjs.com/package/jsonresume-theme-randytarampi) or finding one where someone's gone through and styled it using all the good `@page` CSS rules and whatnot (which is why my US Legal one is so broken).

**Comment by DustinWehr** [comment]
Forgot I made this issue. I found a solution that's working well for me. See https://github.com/jsonresume/resume-cli/issues/413#issuecomment-750454100

**Comment by DustinWehr** [comment]
My personal needs are satisfied by the PDF24 workflow given here https://github.com/jsonresume/resume-cli/issues/413#issuecomment-750454100.
If there's any desire to generalize and integrate it into the `resume` tool as a hacky-but-working solution, I'm available to help.
