### ISSUE TITLE
Support for markdown export removed?

### ISSUE THREAD

**Issue by tanookiben** [jsonresume/resume-cli#40]
Looking at this commit from a couple weeks ago ([remove md export](https://github.com/jsonresume/resume-cli/commit/d236b0b5ca1901eb5d90816bce770e1d9d6a27da)), it seems like support for markdown exports was removed. Was there a particular reason why?

**Comment by johnny353535** [comment]
Any progress?

**Comment by erming** [comment]
Not yet implemented in the `resume-cli`.

However, there's a theme you can use to render the markdown:

https://github.com/jtwebman/jsonresume-theme-markdown

You use it like this:
```
resume export /path/to/resume.json --theme markdown
```
.. and it will generate resume.html for you (which is really a .md file, though)

If you don't like the layout, you could always fork that theme or create your own.

Hope this helps!

**Comment by chrisdotcode** [comment]
@mchelen:
> I think the markdown export was added after the filename detection, so probably the .md extension needs to be added to the filename detection.

**Comment by thomasdavis** [comment]
Use use the markdown theme instead.

```resume export resume.html --theme markdown```

Or copy it straight from the registry as such

registry.jsonresume.org/thomasdavis?theme=markdown
