### ISSUE TITLE
Also support --resume option for export and test

### ISSUE THREAD

**Issue by Tyilo** [jsonresume/resume-cli#407]

**Comment by aegershman** [comment]
(+1; just posting this for issue tracking, but this appears similar to https://github.com/jsonresume/resume-cli/issues/225 and possibly https://github.com/jsonresume/resume-cli/pull/286)

**Comment by antialias** [comment]
This appears to be resolved with a refactor of getResume. I have a PR up that adds tests to ensure that this issue does not re-appear. https://github.com/jsonresume/resume-cli/pull/459
