### ISSUE TITLE
Provide a HTML GUI wrapper over JSON to build resume quickly.

### ISSUE THREAD

**Issue by vikramsoni2** [jsonresume/resume-cli#43]
Today when I was thinking of making my own resume, I thought it would be very useful if there is a functionality on the website or a standalone SPA to write your resume which generates JSON, PDF etc.

What do you think? I can build something like that.. Let me know your thoughts.

**Comment by chrisdotcode** [comment]
@thomasdavis I think erming/resume-editor should officially be added to the jsonresume organization before we close this.

It's already in production.

**Comment by thomasdavis** [comment]
I think it is okay to let the repos spread outside the org.

That being said, at this point the old resume editor is probably outdated-ish.

And lots of cool tools have popped up to generate forms from JSON schemas, e.g. a react form generator -> http://mozilla-services.github.io/react-jsonschema-form/
