### ISSUE TITLE
remove update notifier code, or replace with dependency

### ISSUE THREAD

**Issue by antialias** [jsonresume/resume-cli#438]
It is not a core responsibility of resume-cli to ensure that it is up-to-date every time it is run.
I propose that the code that does this either be removed, or that instead of maintaining the code as part of this package, that a package whose purpose is to notify of updates be leveraged. [`update-notifier`](https://www.npmjs.com/package/update-notifier) appears to be well-maintained and popular, so that would probably be a reasonable choice.

Furthermore:
* it appears that the config file is only used to store the last date of the version check, so we can remove `getConfig` from `preFlow` by removing this check
* after removing `getConfig` and `checkPkgVersion` from preFlow, the only things that are left are `getResume`, and `validateSchema`. These functions can be invoked only when needed from inside the handlers for `commander` commands; 

By running `getResume` and `validateSchema` from inside `commander` handlers, they can be be invoked with `export` / `publish` / `test` arguments parsed by `commander` instead of having to parse them manually as documented in https://github.com/jsonresume/resume-cli/issues/435:

```sh
lib/pre-flow/validate-schema.js
4:  const options = process.argv.slice(2);
5:  if (['export', 'publish'].indexOf(process.argv[2]) === -1) {

lib/pre-flow/get-resume.js
6:  process.argv.forEach((arg) => {
13:      if (['export', 'test'].indexOf(process.argv[2]) !== -1) {
```

Finally:
If we can get this far, pre-flow can be removed altogether.

**Comment by thomasdavis** [comment]
Good idea, take it out.
