### ISSUE TITLE
PDF export not working?

### ISSUE THREAD

**Issue by rafaelrinaldi** [jsonresume/resume-cli#44]
Not sure if I'm doing something wrong, but I just tried to generate a PDF file with `resume-cli` without success. See the screen capture:

![export_error](https://i.cloudup.com/bswYIil5rC.gif)

Then, I got the following error when trying to open the file (with Preview.app that comes with OSX):
![export_preview_error](https://i.cloudup.com/PvqgfB2vvD-3000x3000.png)

Any help?

**Comment by Justindmo** [comment]
PDF export still isn't working.
