### ISSUE TITLE
LaTeX output for better PDFs?

### ISSUE THREAD

**Issue by ocram** [jsonresume/resume-cli#52]
Are there any plans to add LaTeX support in addition to HTML?
- There are tons of great (free) LaTeX templates for CVs.
- It's easy to create high-quality CVs in LaTeX.
- The current PDF output is `still ugly` (quote from homepage).

Rendering LaTeX to PDF doesn't have to be part of that support, of course. You can compile the LaTeX on your computer or [online](https://www.sharelatex.com/) but having LaTeX output from the JSON Resume tools would be great.

**Comment by scottsievert** [comment]
+1

**Comment by rosshadden** [comment]
@djengineerllc I don't think that's true.  I use `json_resume` (and was looking for something else since development has ceased).  If you don't have `pdflatex`, it throws an error.  Maybe on Windows or some other environment it uses an external service, but on Linux it compiles it on your computer.

**Comment by thomasdavis** [comment]
There hasn't been much push for a resume.json to latex. 

The best so far is https://github.com/ianprime0509/jsonresume-theme-latex
