### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by JaredCubilla** [jsonresume/resume-cli#55]
Hey there, I've created a [repository](https://github.com/JaredCubilla/jsonresume-backwards-compatibility) for converting, invalid, pre-release versions of `resume.json` files and turning them into valid 0.0.0 files.

Is it possible to add something like this to the resume-cli so users won't have to spend all that time changing their `resume.json` file? I'm very new to Node.js so I'm not sure if this would work or not.

**Comment by chrisdotcode** [comment]
Or probably, what would be better: an upgrade command that converts from the last resume-schema version to the current.

If you want to use an older version of the schema, just don't upgrade the resume cli.

**Comment by thomasdavis** [comment]
This was great work, we will require something soon. 

Linking the original repo for reference https://github.com/JaredCubilla/jsonresume-backwards-compatibility
