### ISSUE TITLE
Documentation on serve

### ISSUE THREAD

**Issue by assimilate-dev** [jsonresume/resume-cli#563]
I'm looking to host a resume and attempting to install certificates.

From the readme:
Starts a web server that serves your local `resume.json`

Is there documentation on the type of webserver so that I am able to install certificates?

**Comment by thomasdavis** [comment]
@assimilate-dev the `serve` command just `export`'s your resume to a theme locally and then makes a node server that host the public assets to display it. 

So you might just want to export your resume to a theme and host it whereever you want.

**Comment by SethFalco** [comment]
I'll mark this as a documentation task. The `serve` command is not intended for production use, it's a convenience intended for theme development or to visualize changes to your theme while editing.

I'll get the README updated to clarify this.
