### ISSUE TITLE
"endDate": null should be equivalent to not having endDate

### ISSUE THREAD

**Issue by dbkaplun** [jsonresume/resume-cli#60]

**Comment by errakeshpd** [comment]
Same error when i used any of the themes available, i changed main.js - > var theme = "kendal"
if i used default theme also same error is occuring , Please find the attached image

![date_error](https://cloud.githubusercontent.com/assets/5379778/5890666/ab185f7a-a48c-11e4-80df-0dccd1023d85.png)

**Comment by errakeshpd** [comment]
whats the actual input format want to give for these date fields ?

**Comment by errakeshpd** [comment]
after i remove the lines like "date" for all the above scenerios then also the same errors are triggering !!!

**Comment by carlvlewis** [comment]
Hey, @errakeshpd, the actual input is 'yyyy-mm-dd' according to most of the templates using the schema. So you'll need to change the values you have set for date to actual dates...

**Comment by errakeshpd** [comment]
Hi @carlvlewis , I also followed the same format, Like - 2015-05-01  => 'yyyy-mm-dd' 
and I also want to mention that the default template provided by the system also trigger the same error (Richard Hendriks Profile).

**Comment by mchelen** [comment]
@errakeshpd Can you post a snippet of the JSON you are using?
Also the flag to force export is `-F` or `--force` not `-f`

**Comment by errakeshpd** [comment]
@mchelen  --force :+1: its worked !!

**Comment by mchelen** [comment]
@errakeshpd Great, glad that worked!

**Comment by rolandnsharp** [comment]
Okay where are we at with this issue? Do we want this to work without having to use `force` or is that a valid option? I'll do what I can to resolve this issue asap.

**Comment by chrisdotcode** [comment]
This is a schema issue, cf. jsonresume/resume-schema#199

**Comment by HeidiHansen** [comment]
This is still an issue.  One should be able to show a single date without Present/Current following it.  What about an event I volunteered for one year or a class that was only 1 month long?  "2015 - 2015" Looks stupid.  "2015 - Present" isn't accurate.  I've read all the related threads and haven't found a solution for this.  Anyone else interested in this?
