### ISSUE TITLE
Cloned themes as git submodules, installed them, but can't export as PDF?

### ISSUE THREAD

**Issue by Nezteb** [jsonresume/resume-cli#685]
I made a `themes` directory and then added two themes to it as git submodules:
- `git submodule add git@github.com:davcd/jsonresume-theme-actual.git themes/actual`
- `git submodule add git@github.com:kelyvin/jsonresume-theme-caffeine.git themes/caffeine`

Directory structure:
```
❯ tree -L 2
.
├── README.md
├── example.json
├── index.html
├── node_modules
│   └── ...
├── package-lock.json
├── package.json
├── public
│   └── index.html
├── resume.json
├── resume.pdf
├── themes
│   ├── actual
│   └── caffeine
└── yarn.lock
```

I `cd`'d into each theme directory and ran `npm install`, each command succeeded, then went back to the root. I tried running `npm install ./themes/actual` for each theme from the root too.

HTML exports work fine for both themes using: `resume export --theme ./themes/actual index.html`

However, PDF does not work when running: `resume export --theme ./themes/actual resume.pdf`.

When I run it, I get the following error regardless of the theme:

`You have to install this theme relative to the folder to use it e.g. 'npm install /Users/nezteb/Git/resume/index.js'`

Using Node version 12.22.6 (I tried with 16 and got lots of Node/GYP errors when installing each theme).

**Comment by chessmango** [comment]
Related: https://github.com/jsonresume/resume-cli/issues/408#issuecomment-1060030481
I haven't tested specifying a theme manually (as that's what that issue covers and what was at least semi-fixed) - I'm using `even` because it's pretty and gets the job done :P but that worked with 3.0.5 as expected, before the fix above at least

**Comment by Nezteb** [comment]
Here is a PR to fix this issue: https://github.com/jsonresume/resume-cli/pull/689
