### ISSUE TITLE
External CSS/JS files in themes break on HTML/PDF export

### ISSUE THREAD

**Issue by mchelen** [jsonresume/resume-cli#69]
Any theme that has an external CSS/JS file referenced like:
`//cdnjs.cloudflare.com/ajax/libs/polymer/0.3.4/platform.js`
only works with HTML export if the file is served over a server, but does not work if the file is loaded directly in the browser.
All PDF exports with external assets like this are also broken.
Where should this behavior be fixed, in the theme, HTML export, or PDF export stage?

**Comment by chrisdotcode** [comment]
This is a part of #169.
