### ISSUE TITLE
Setting up custom domain for your resume url

### ISSUE THREAD

**Issue by mudassir0909** [jsonresume/resume-cli#70]
We can have "Powered by jsonresume" in the footer if we want to.

**Comment by iansinnott** [comment]
Custom URLs would be great :+1:

**Comment by mchelen** [comment]
A workaround for now is to have your domain load the URL in an `<iframe>`.

**Comment by santiago26** [comment]
Maybe you can consider publishing in HTML to Github pages.

**Comment by justsml** [comment]
+1 @santiago26 
github pages are the way to go...

**Comment by thomasdavis** [comment]
Custom domains are only supported via self hosting.
