### ISSUE TITLE
themes.jsonresume.org is down 

### ISSUE THREAD

**Issue by SeaifanAladdin** [jsonresume/resume-cli#766]
Getting this error from CLI
There was an error downloading your generated html resume from our server: Error: getaddrinfo ENOTFOUND themes.jsonresume.org

Also getting Browser Error: We can’t connect to the server at themes.jsonresume.org

**Comment by vanhoutenbos** [comment]
Seems like it has been down for a while assuming by the last issues that have been made. Not sure if the project has been abandoned or something

**Comment by thomasdavis** [comment]
Ahhh there is a new server for the theme functionality, I will look into it.

**Comment by thomasdavis** [comment]
There is no endpoint for themes right now. There is a page https://registry.jsonresume.org/themes

Let me know if there is demand for an api listing
