### ISSUE TITLE
Read resume from stdin

### ISSUE THREAD

**Issue by jimguistwite** [jsonresume/resume-cli#81]
I am using jq to modify the json in order to generate custom versions of my resume for different needs.  It would be a nice enhancement if I could simply run "jq < resume.json | resume export --format html" rather then generating a temporary file.

**Comment by thomasdavis** [comment]
I don't think you would ever get to create a full resume in on seating so don't imagine ever just having a full resume.json temporarily in memory while you jq. Going to leave this one out of the cli repo.
