### ISSUE TITLE
Theme name must be specified in small characters

### ISSUE THREAD

**Issue by poleveD** [jsonresume/resume-cli#87]
While the documentation indicates the option of specifying a theme name, it does not explicitly say that the name must be provided in "all small letters" only.

Either mention the same or fix the tool to accept the name as mentioned on in "https://jsonresume.org/themes/"

**Comment by poleveD** [comment]
Just realized that this issue can be fixed in "https://github.com/jsonresume/theme-manager/blob/master/lib/theme.js" line 69 by converting the theme parameter to small-case!

**Comment by mchelen** [comment]
That seems like a valid way to fix to the problem. The theme names are dependent on the NPM package name, and AFAIK those package names must be lower case. So any input of an upper case theme name can safely be converted to lower case.

**Comment by poleveD** [comment]
@mchelen fyi, I fixed resume-cli and created a pull request.

**Comment by thomasdavis** [comment]
Merged in the fix, thanks again@poleveD!
