### ISSUE TITLE
Hosted exported versions

### ISSUE THREAD

**Issue by tateman66** [jsonresume/resume-cli#88]
Hey Guys.

Am I kinda stupid here?  Don't answer that!
How after a  normal publish do I get the exported versions hosted as well.

I get the standard - you need to publish page.  I guess it's not 'magic' that the /thomasdavis.pdf gets generated?

Thanks,
Steven

**Comment by mchelen** [comment]
It looks like you are doing everything properly, you just need to publish and then all formats should be automatically available. But there seems to be a bug https://github.com/jsonresume/registry-server/issues/37
