### ISSUE TITLE
Add proxy support for network connections

### ISSUE THREAD

**Issue by droidekas** [jsonresume/resume-cli#89]
command used:  `resume export Resumepdf`

error encountered:
`events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)`

**Comment by mchelen** [comment]
Hmm I just tested the same command and it worked fine. Can you try again & confirm? Also for reference, what does `resume -V` show?

**Comment by satyarth** [comment]
So i checked it again.Its a proxy issue.I have set npm and node for my default proxy settings.So are you inheriting these settings?Or do you have a config to set it up?Because i could not find any such area.

**Comment by mchelen** [comment]
Ah ok, I don't know if resume-cli has any particular support for proxies.

**Comment by thomasdavis** [comment]
Pretty sure you can do this at a lower level and I don't think it is in the scope of this project.
