### ISSUE TITLE
Crash on export error, instead of writing said error to a file

### ISSUE THREAD

**Issue by mchelen** [jsonresume/resume-cli#90]
Trying to export a resume using an invalid theme currently does not show any errors.
For example,
```
resume export resume.html --theme foobar
```
Will show no errors, say "Done!" and create an empty HTML with the text "Theme could not be found in the npm registry."

**Comment by poleveD** [comment]
@mchelen I forked and modified exportResume code, however could not verify. Would you please look into https://github.com/poleveD/resume-cli?

How does one run this code and test in local?

**Comment by mchelen** [comment]
@poleveD You couldn't reproduce the non-error, or could not fix the problem? I think the issue might actually be in `registry-server`.
In general the way to run `resume-cli` locally is cd'ing into the directory, and running `node index.js`.

**Comment by poleveD** [comment]
@mchelen I changed the code to fix the export .html issue but could not test it out. From your comment, I gathered the idea to run the resume-cli locally and currently debugging the issue. Shall come back with more details.

**Comment by mchelen** [comment]
@poleveD Ok awesome, let me know if there are any more questions I can help with.

**Comment by poleveD** [comment]
@mchelen I created a pull request https://github.com/jsonresume/resume-cli/pull/92 to fix this issue.

But the actual issue must be fixed in the server - please see my pull request comments for details.

**Comment by mchelen** [comment]
@poleveD That looks great, thanks! Do you want to try modifying `registry-server` to return a proper error response? Here is some info on how to make `resume-cli` connect to a development instance of `registry-server` https://github.com/jsonresume/resume-docs/wiki/Resume-CLI

**Comment by poleveD** [comment]
@mchelen will do, thanks for that reference! Meanwhile, can you please confirm that the temp fix works?

**Comment by chrisdotcode** [comment]
We *should* have the server return some sort of error here. And when we get that error, we should crash with it.

**Comment by thomasdavis** [comment]
Added in `0.4.11`

**Comment by thomasdavis** [comment]
For anyone wondering, the cli tool hits the themes server directly.

If you send a POST request with a payload to http://themes.jsonresume.org/theme/direct, you will get html back.
