### ISSUE TITLE
Serve command is broken

### ISSUE THREAD

**Issue by adius** [jsonresume/resume-cli#97]
Seems like there is nothing working at all =D

```
$ resume serve

Preview: http://localhost:4000
Press ctrl-c to stop


module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/adrian/Sites/adius.github.io/index'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/resume-cli/lib/builder.js:43:18
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

**Comment by thomasdavis** [comment]
So I think resume serve was implemented quickly as a feature for theme developers.

Try cloning https://github.com/jsonresume/jsonresume-theme-boilerplate and then running `resume serve` inside that directory.

**Comment by jkyuusai** [comment]
The serve command definitely works, I'm running it off a forked copy of https://github.com/isnotahippy/jsonresume-theme-short right now. 

I just ran `resume serve` in my home dir and got that error message. I would guess that error gets thrown when serve isn't running inside a directory with a theme set up in it. As @thomasdavis said, `serve` looks like it's built right now explicitly for use with developing themes. 

If you want to use it to work on your resume itself:
1. Find the repo for a theme that suits you and clone it
2. Place a copy of your resume saved as `resume.json` inside the cloned repo
3. Run `resume serve` inside the cloned repo

Your resume should then be accessible at http://localhost:4000

**Comment by chrisdotcode** [comment]
> So I think resume serve was implemented quickly as a feature for theme developers.
>
> The serve command definitely works
>
> As @thomasdavis said, serve looks like it's built right now explicitly for use with developing themes.

So it seems that `serve` does work, but not necessarily in the way @adius expected.

**Comment by houtianze** [comment]
How can `resume serve` be considered *working* when `resume export` works without those unnecessary directory(ies) while `resume serve` does not?
