### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mchelen** [jsonresume/resume-cli#99]
create unit tests for as many commands as possible
- [ ] `resume init`
- [ ] `resume serve`

**Comment by rolandnsharp** [comment]
@mchelen , do you have any ideas on how to mock out the `read` terminal inputs?

I can't figure out how to write these tests because I can't get progress the function passed:

```
read({
        prompt: 'name: '
    }, function(er, name) {
        if (er) {
            console.log();
            process.exit();
       })
```
for example.

Any ideas?

**Comment by rolandnsharp** [comment]
So from the `read` documentation it looks like we need to use a readable stream. 
`input Readable stream to get input data from. (default process.stdin)`

Starting with `var Readable = require('stream').Readable;`

If someone could help me understand what needs to be done I'll write all the tests we need. Thanks.
